package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListAttachinterfaces
type ListAttachinterfacesRequest struct{
    serverID string
}

func NewListAttachinterfacesRequest()*ListAttachinterfacesRequest{
    return &ListAttachinterfacesRequest{}
}

//response struct for the ListAttachinterfaces
type ListAttachinterfacesResponse struct{
    Pager pagination.Pager
}

func NewListAttachinterfacesResponse(pager pagination.Pager,)*ListAttachinterfacesResponse {
    return &ListAttachinterfacesResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListAttachinterfaces(request *ListAttachinterfacesRequest)(*ListAttachinterfacesResponse){
    return NewListAttachinterfacesResponse(attachinterfaces.List(oc.client,request.serverID, ))

}
//request struct for the GetAttachinterfaces
type GetAttachinterfacesRequest struct{
    serverID string
    portID string
}

func NewGetAttachinterfacesRequest()*GetAttachinterfacesRequest{
    return &GetAttachinterfacesRequest{}
}

//response struct for the GetAttachinterfaces
type GetAttachinterfacesResponse struct{
    GetResult attachinterfaces.GetResult
}

func NewGetAttachinterfacesResponse(getResult attachinterfaces.GetResult,)*GetAttachinterfacesResponse {
    return &GetAttachinterfacesResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetAttachinterfaces(request *GetAttachinterfacesRequest)(*GetAttachinterfacesResponse){
    return NewGetAttachinterfacesResponse(attachinterfaces.Get(oc.client,request.serverID,request.portID, ))

}
//request struct for the CreateAttachinterfaces
type CreateAttachinterfacesRequest struct{
    serverID string
    opts attachinterfaces.CreateOptsBuilder
}

func NewCreateAttachinterfacesRequest()*CreateAttachinterfacesRequest{
    return &CreateAttachinterfacesRequest{}
}

//response struct for the CreateAttachinterfaces
type CreateAttachinterfacesResponse struct{
    CreateResult attachinterfaces.CreateResult
}

func NewCreateAttachinterfacesResponse(createResult attachinterfaces.CreateResult,)*CreateAttachinterfacesResponse {
    return &CreateAttachinterfacesResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateAttachinterfaces(request *CreateAttachinterfacesRequest)(*CreateAttachinterfacesResponse){
    return NewCreateAttachinterfacesResponse(attachinterfaces.Create(oc.client,request.serverID,request.opts, ))

}
//request struct for the DeleteAttachinterfaces
type DeleteAttachinterfacesRequest struct{
    serverID string
    portID string
}

func NewDeleteAttachinterfacesRequest()*DeleteAttachinterfacesRequest{
    return &DeleteAttachinterfacesRequest{}
}

//response struct for the DeleteAttachinterfaces
type DeleteAttachinterfacesResponse struct{
    DeleteResult attachinterfaces.DeleteResult
}

func NewDeleteAttachinterfacesResponse(deleteResult attachinterfaces.DeleteResult,)*DeleteAttachinterfacesResponse {
    return &DeleteAttachinterfacesResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteAttachinterfaces(request *DeleteAttachinterfacesRequest)(*DeleteAttachinterfacesResponse){
    return NewDeleteAttachinterfacesResponse(attachinterfaces.Delete(oc.client,request.serverID,request.portID, ))

}