package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/backups"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateBlockstorageExtensionsBackups
type CreateBlockstorageExtensionsBackupsRequest struct{
    Opts backups.CreateOpts
}

func NewCreateBlockstorageExtensionsBackupsRequest()*CreateBlockstorageExtensionsBackupsRequest{
    return &CreateBlockstorageExtensionsBackupsRequest{}
}

//response struct for the CreateBlockstorageExtensionsBackups
type CreateBlockstorageExtensionsBackupsResponse struct{
    CreateResult backups.CreateResult
}

func NewCreateBlockstorageExtensionsBackupsResponse(createResult backups.CreateResult,)*CreateBlockstorageExtensionsBackupsResponse {
    return &CreateBlockstorageExtensionsBackupsResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateBlockstorageExtensionsBackups(req *CreateBlockstorageExtensionsBackupsRequest)(*CreateBlockstorageExtensionsBackupsResponse){
    return NewCreateBlockstorageExtensionsBackupsResponse(backups.Create(oc.Client,req.Opts, ))

}
//request struct for the DeleteBlockstorageExtensionsBackups
type DeleteBlockstorageExtensionsBackupsRequest struct{
    Id string
}

func NewDeleteBlockstorageExtensionsBackupsRequest()*DeleteBlockstorageExtensionsBackupsRequest{
    return &DeleteBlockstorageExtensionsBackupsRequest{}
}

//response struct for the DeleteBlockstorageExtensionsBackups
type DeleteBlockstorageExtensionsBackupsResponse struct{
    DeleteResult backups.DeleteResult
}

func NewDeleteBlockstorageExtensionsBackupsResponse(deleteResult backups.DeleteResult,)*DeleteBlockstorageExtensionsBackupsResponse {
    return &DeleteBlockstorageExtensionsBackupsResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteBlockstorageExtensionsBackups(req *DeleteBlockstorageExtensionsBackupsRequest)(*DeleteBlockstorageExtensionsBackupsResponse){
    return NewDeleteBlockstorageExtensionsBackupsResponse(backups.Delete(oc.Client,req.Id, ))

}
//request struct for the GetBlockstorageExtensionsBackups
type GetBlockstorageExtensionsBackupsRequest struct{
    Id string
}

func NewGetBlockstorageExtensionsBackupsRequest()*GetBlockstorageExtensionsBackupsRequest{
    return &GetBlockstorageExtensionsBackupsRequest{}
}

//response struct for the GetBlockstorageExtensionsBackups
type GetBlockstorageExtensionsBackupsResponse struct{
    GetResult backups.GetResult
}

func NewGetBlockstorageExtensionsBackupsResponse(getResult backups.GetResult,)*GetBlockstorageExtensionsBackupsResponse {
    return &GetBlockstorageExtensionsBackupsResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetBlockstorageExtensionsBackups(req *GetBlockstorageExtensionsBackupsRequest)(*GetBlockstorageExtensionsBackupsResponse){
    return NewGetBlockstorageExtensionsBackupsResponse(backups.Get(oc.Client,req.Id, ))

}
//request struct for the ListBlockstorageExtensionsBackups
type ListBlockstorageExtensionsBackupsRequest struct{
    Opts backups.ListOpts
}

func NewListBlockstorageExtensionsBackupsRequest()*ListBlockstorageExtensionsBackupsRequest{
    return &ListBlockstorageExtensionsBackupsRequest{}
}

//response struct for the ListBlockstorageExtensionsBackups
type ListBlockstorageExtensionsBackupsResponse struct{
    Pager pagination.Pager
}

func NewListBlockstorageExtensionsBackupsResponse(pager pagination.Pager,)*ListBlockstorageExtensionsBackupsResponse {
    return &ListBlockstorageExtensionsBackupsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListBlockstorageExtensionsBackups(req *ListBlockstorageExtensionsBackupsRequest)(*ListBlockstorageExtensionsBackupsResponse){
    return NewListBlockstorageExtensionsBackupsResponse(backups.List(oc.Client,req.Opts, ))

}
//request struct for the ListDetailBlockstorageExtensionsBackups
type ListDetailBlockstorageExtensionsBackupsRequest struct{
    Opts backups.ListDetailOpts
}

func NewListDetailBlockstorageExtensionsBackupsRequest()*ListDetailBlockstorageExtensionsBackupsRequest{
    return &ListDetailBlockstorageExtensionsBackupsRequest{}
}

//response struct for the ListDetailBlockstorageExtensionsBackups
type ListDetailBlockstorageExtensionsBackupsResponse struct{
    Pager pagination.Pager
}

func NewListDetailBlockstorageExtensionsBackupsResponse(pager pagination.Pager,)*ListDetailBlockstorageExtensionsBackupsResponse {
    return &ListDetailBlockstorageExtensionsBackupsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListDetailBlockstorageExtensionsBackups(req *ListDetailBlockstorageExtensionsBackupsRequest)(*ListDetailBlockstorageExtensionsBackupsResponse){
    return NewListDetailBlockstorageExtensionsBackupsResponse(backups.ListDetail(oc.Client,req.Opts, ))

}
//request struct for the UpdateBlockstorageExtensionsBackups
type UpdateBlockstorageExtensionsBackupsRequest struct{
    Id string
    Opts backups.UpdateOpts
}

func NewUpdateBlockstorageExtensionsBackupsRequest()*UpdateBlockstorageExtensionsBackupsRequest{
    return &UpdateBlockstorageExtensionsBackupsRequest{}
}

//response struct for the UpdateBlockstorageExtensionsBackups
type UpdateBlockstorageExtensionsBackupsResponse struct{
    UpdateResult backups.UpdateResult
}

func NewUpdateBlockstorageExtensionsBackupsResponse(updateResult backups.UpdateResult,)*UpdateBlockstorageExtensionsBackupsResponse {
    return &UpdateBlockstorageExtensionsBackupsResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateBlockstorageExtensionsBackups(req *UpdateBlockstorageExtensionsBackupsRequest)(*UpdateBlockstorageExtensionsBackupsResponse){
    return NewUpdateBlockstorageExtensionsBackupsResponse(backups.Update(oc.Client,req.Id,req.Opts, ))

}
//request struct for the RestoreFromBackupBlockstorageExtensionsBackups
type RestoreFromBackupBlockstorageExtensionsBackupsRequest struct{
    Id string
    Opts backups.RestoreOpts
}

func NewRestoreFromBackupBlockstorageExtensionsBackupsRequest()*RestoreFromBackupBlockstorageExtensionsBackupsRequest{
    return &RestoreFromBackupBlockstorageExtensionsBackupsRequest{}
}

//response struct for the RestoreFromBackupBlockstorageExtensionsBackups
type RestoreFromBackupBlockstorageExtensionsBackupsResponse struct{
    RestoreResult backups.RestoreResult
}

func NewRestoreFromBackupBlockstorageExtensionsBackupsResponse(restoreResult backups.RestoreResult,)*RestoreFromBackupBlockstorageExtensionsBackupsResponse {
    return &RestoreFromBackupBlockstorageExtensionsBackupsResponse{
            RestoreResult:restoreResult,
    }
}

// action function
func (oc *OpenstackClient) RestoreFromBackupBlockstorageExtensionsBackups(req *RestoreFromBackupBlockstorageExtensionsBackupsRequest)(*RestoreFromBackupBlockstorageExtensionsBackupsResponse){
    return NewRestoreFromBackupBlockstorageExtensionsBackupsResponse(backups.RestoreFromBackup(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ExportBlockstorageExtensionsBackups
type ExportBlockstorageExtensionsBackupsRequest struct{
    Id string
}

func NewExportBlockstorageExtensionsBackupsRequest()*ExportBlockstorageExtensionsBackupsRequest{
    return &ExportBlockstorageExtensionsBackupsRequest{}
}

//response struct for the ExportBlockstorageExtensionsBackups
type ExportBlockstorageExtensionsBackupsResponse struct{
    ExportResult backups.ExportResult
}

func NewExportBlockstorageExtensionsBackupsResponse(exportResult backups.ExportResult,)*ExportBlockstorageExtensionsBackupsResponse {
    return &ExportBlockstorageExtensionsBackupsResponse{
            ExportResult:exportResult,
    }
}

// action function
func (oc *OpenstackClient) ExportBlockstorageExtensionsBackups(req *ExportBlockstorageExtensionsBackupsRequest)(*ExportBlockstorageExtensionsBackupsResponse){
    return NewExportBlockstorageExtensionsBackupsResponse(backups.Export(oc.Client,req.Id, ))

}
//request struct for the ImportBlockstorageExtensionsBackups
type ImportBlockstorageExtensionsBackupsRequest struct{
    Opts backups.ImportOpts
}

func NewImportBlockstorageExtensionsBackupsRequest()*ImportBlockstorageExtensionsBackupsRequest{
    return &ImportBlockstorageExtensionsBackupsRequest{}
}

//response struct for the ImportBlockstorageExtensionsBackups
type ImportBlockstorageExtensionsBackupsResponse struct{
    ImportResult backups.ImportResult
}

func NewImportBlockstorageExtensionsBackupsResponse(importResult backups.ImportResult,)*ImportBlockstorageExtensionsBackupsResponse {
    return &ImportBlockstorageExtensionsBackupsResponse{
            ImportResult:importResult,
    }
}

// action function
func (oc *OpenstackClient) ImportBlockstorageExtensionsBackups(req *ImportBlockstorageExtensionsBackupsRequest)(*ImportBlockstorageExtensionsBackupsResponse){
    return NewImportBlockstorageExtensionsBackupsResponse(backups.Import(oc.Client,req.Opts, ))

}