package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/clustering/v1/receivers"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateClusteringV1Receivers
type CreateClusteringV1ReceiversRequest struct{
    Opts receivers.CreateOptsBuilder
}

func NewCreateClusteringV1ReceiversRequest()*CreateClusteringV1ReceiversRequest{
    return &CreateClusteringV1ReceiversRequest{}
}

//response struct for the CreateClusteringV1Receivers
type CreateClusteringV1ReceiversResponse struct{
    CreateResult receivers.CreateResult
}

func NewCreateClusteringV1ReceiversResponse(createResult receivers.CreateResult,)*CreateClusteringV1ReceiversResponse {
    return &CreateClusteringV1ReceiversResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateClusteringV1Receivers(req *CreateClusteringV1ReceiversRequest)(*CreateClusteringV1ReceiversResponse){
    return NewCreateClusteringV1ReceiversResponse(receivers.Create(oc.client,req.Opts, ))

}
//request struct for the UpdateClusteringV1Receivers
type UpdateClusteringV1ReceiversRequest struct{
    Id string
    Opts receivers.UpdateOptsBuilder
}

func NewUpdateClusteringV1ReceiversRequest()*UpdateClusteringV1ReceiversRequest{
    return &UpdateClusteringV1ReceiversRequest{}
}

//response struct for the UpdateClusteringV1Receivers
type UpdateClusteringV1ReceiversResponse struct{
    UpdateResult receivers.UpdateResult
}

func NewUpdateClusteringV1ReceiversResponse(updateResult receivers.UpdateResult,)*UpdateClusteringV1ReceiversResponse {
    return &UpdateClusteringV1ReceiversResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateClusteringV1Receivers(req *UpdateClusteringV1ReceiversRequest)(*UpdateClusteringV1ReceiversResponse){
    return NewUpdateClusteringV1ReceiversResponse(receivers.Update(oc.client,req.Id,req.Opts, ))

}
//request struct for the GetClusteringV1Receivers
type GetClusteringV1ReceiversRequest struct{
    Id string
}

func NewGetClusteringV1ReceiversRequest()*GetClusteringV1ReceiversRequest{
    return &GetClusteringV1ReceiversRequest{}
}

//response struct for the GetClusteringV1Receivers
type GetClusteringV1ReceiversResponse struct{
    GetResult receivers.GetResult
}

func NewGetClusteringV1ReceiversResponse(getResult receivers.GetResult,)*GetClusteringV1ReceiversResponse {
    return &GetClusteringV1ReceiversResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetClusteringV1Receivers(req *GetClusteringV1ReceiversRequest)(*GetClusteringV1ReceiversResponse){
    return NewGetClusteringV1ReceiversResponse(receivers.Get(oc.client,req.Id, ))

}
//request struct for the ListClusteringV1Receivers
type ListClusteringV1ReceiversRequest struct{
    Opts receivers.ListOptsBuilder
}

func NewListClusteringV1ReceiversRequest()*ListClusteringV1ReceiversRequest{
    return &ListClusteringV1ReceiversRequest{}
}

//response struct for the ListClusteringV1Receivers
type ListClusteringV1ReceiversResponse struct{
    Pager pagination.Pager
}

func NewListClusteringV1ReceiversResponse(pager pagination.Pager,)*ListClusteringV1ReceiversResponse {
    return &ListClusteringV1ReceiversResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListClusteringV1Receivers(req *ListClusteringV1ReceiversRequest)(*ListClusteringV1ReceiversResponse){
    return NewListClusteringV1ReceiversResponse(receivers.List(oc.client,req.Opts, ))

}
//request struct for the DeleteClusteringV1Receivers
type DeleteClusteringV1ReceiversRequest struct{
    Id string
}

func NewDeleteClusteringV1ReceiversRequest()*DeleteClusteringV1ReceiversRequest{
    return &DeleteClusteringV1ReceiversRequest{}
}

//response struct for the DeleteClusteringV1Receivers
type DeleteClusteringV1ReceiversResponse struct{
    DeleteResult receivers.DeleteResult
}

func NewDeleteClusteringV1ReceiversResponse(deleteResult receivers.DeleteResult,)*DeleteClusteringV1ReceiversResponse {
    return &DeleteClusteringV1ReceiversResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteClusteringV1Receivers(req *DeleteClusteringV1ReceiversRequest)(*DeleteClusteringV1ReceiversResponse){
    return NewDeleteClusteringV1ReceiversResponse(receivers.Delete(oc.client,req.Id, ))

}
//request struct for the NotifyClusteringV1Receivers
type NotifyClusteringV1ReceiversRequest struct{
    Id string
}

func NewNotifyClusteringV1ReceiversRequest()*NotifyClusteringV1ReceiversRequest{
    return &NotifyClusteringV1ReceiversRequest{}
}

//response struct for the NotifyClusteringV1Receivers
type NotifyClusteringV1ReceiversResponse struct{
    NotifyResult receivers.NotifyResult
}

func NewNotifyClusteringV1ReceiversResponse(notifyResult receivers.NotifyResult,)*NotifyClusteringV1ReceiversResponse {
    return &NotifyClusteringV1ReceiversResponse{
            NotifyResult:notifyResult,
    }
}

// action function
func (oc *OpenstackClient) NotifyClusteringV1Receivers(req *NotifyClusteringV1ReceiversRequest)(*NotifyClusteringV1ReceiversResponse){
    return NewNotifyClusteringV1ReceiversResponse(receivers.Notify(oc.client,req.Id, ))

}