package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/clustering/v1/policies"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListClusteringV1Policies
type ListClusteringV1PoliciesRequest struct{
    Opts policies.ListOptsBuilder
}

func NewListClusteringV1PoliciesRequest()*ListClusteringV1PoliciesRequest{
    return &ListClusteringV1PoliciesRequest{}
}

//response struct for the ListClusteringV1Policies
type ListClusteringV1PoliciesResponse struct{
    Pager pagination.Pager
}

func NewListClusteringV1PoliciesResponse(pager pagination.Pager,)*ListClusteringV1PoliciesResponse {
    return &ListClusteringV1PoliciesResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListClusteringV1Policies(req *ListClusteringV1PoliciesRequest)(*ListClusteringV1PoliciesResponse){
    return NewListClusteringV1PoliciesResponse(policies.List(oc.client,req.Opts, ))

}
//request struct for the CreateClusteringV1Policies
type CreateClusteringV1PoliciesRequest struct{
    Opts policies.CreateOptsBuilder
}

func NewCreateClusteringV1PoliciesRequest()*CreateClusteringV1PoliciesRequest{
    return &CreateClusteringV1PoliciesRequest{}
}

//response struct for the CreateClusteringV1Policies
type CreateClusteringV1PoliciesResponse struct{
    CreateResult policies.CreateResult
}

func NewCreateClusteringV1PoliciesResponse(createResult policies.CreateResult,)*CreateClusteringV1PoliciesResponse {
    return &CreateClusteringV1PoliciesResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateClusteringV1Policies(req *CreateClusteringV1PoliciesRequest)(*CreateClusteringV1PoliciesResponse){
    return NewCreateClusteringV1PoliciesResponse(policies.Create(oc.client,req.Opts, ))

}
//request struct for the DeleteClusteringV1Policies
type DeleteClusteringV1PoliciesRequest struct{
    PolicyID string
}

func NewDeleteClusteringV1PoliciesRequest()*DeleteClusteringV1PoliciesRequest{
    return &DeleteClusteringV1PoliciesRequest{}
}

//response struct for the DeleteClusteringV1Policies
type DeleteClusteringV1PoliciesResponse struct{
    DeleteResult policies.DeleteResult
}

func NewDeleteClusteringV1PoliciesResponse(deleteResult policies.DeleteResult,)*DeleteClusteringV1PoliciesResponse {
    return &DeleteClusteringV1PoliciesResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteClusteringV1Policies(req *DeleteClusteringV1PoliciesRequest)(*DeleteClusteringV1PoliciesResponse){
    return NewDeleteClusteringV1PoliciesResponse(policies.Delete(oc.client,req.PolicyID, ))

}
//request struct for the UpdateClusteringV1Policies
type UpdateClusteringV1PoliciesRequest struct{
    Id string
    Opts policies.UpdateOptsBuilder
}

func NewUpdateClusteringV1PoliciesRequest()*UpdateClusteringV1PoliciesRequest{
    return &UpdateClusteringV1PoliciesRequest{}
}

//response struct for the UpdateClusteringV1Policies
type UpdateClusteringV1PoliciesResponse struct{
    UpdateResult policies.UpdateResult
}

func NewUpdateClusteringV1PoliciesResponse(updateResult policies.UpdateResult,)*UpdateClusteringV1PoliciesResponse {
    return &UpdateClusteringV1PoliciesResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateClusteringV1Policies(req *UpdateClusteringV1PoliciesRequest)(*UpdateClusteringV1PoliciesResponse){
    return NewUpdateClusteringV1PoliciesResponse(policies.Update(oc.client,req.Id,req.Opts, ))

}
//request struct for the ValidateClusteringV1Policies
type ValidateClusteringV1PoliciesRequest struct{
    Opts policies.ValidateOptsBuilder
}

func NewValidateClusteringV1PoliciesRequest()*ValidateClusteringV1PoliciesRequest{
    return &ValidateClusteringV1PoliciesRequest{}
}

//response struct for the ValidateClusteringV1Policies
type ValidateClusteringV1PoliciesResponse struct{
    ValidateResult policies.ValidateResult
}

func NewValidateClusteringV1PoliciesResponse(validateResult policies.ValidateResult,)*ValidateClusteringV1PoliciesResponse {
    return &ValidateClusteringV1PoliciesResponse{
            ValidateResult:validateResult,
    }
}

// action function
func (oc *OpenstackClient) ValidateClusteringV1Policies(req *ValidateClusteringV1PoliciesRequest)(*ValidateClusteringV1PoliciesResponse){
    return NewValidateClusteringV1PoliciesResponse(policies.Validate(oc.client,req.Opts, ))

}
//request struct for the GetClusteringV1Policies
type GetClusteringV1PoliciesRequest struct{
    PolicyTypeName string
}

func NewGetClusteringV1PoliciesRequest()*GetClusteringV1PoliciesRequest{
    return &GetClusteringV1PoliciesRequest{}
}

//response struct for the GetClusteringV1Policies
type GetClusteringV1PoliciesResponse struct{
    GetResult policies.GetResult
}

func NewGetClusteringV1PoliciesResponse(getResult policies.GetResult,)*GetClusteringV1PoliciesResponse {
    return &GetClusteringV1PoliciesResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetClusteringV1Policies(req *GetClusteringV1PoliciesRequest)(*GetClusteringV1PoliciesResponse){
    return NewGetClusteringV1PoliciesResponse(policies.Get(oc.client,req.PolicyTypeName, ))

}