package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/clustering/v1/policytypes"
)
//request struct for the GetClusteringV1Policytypes
type GetClusteringV1PolicytypesRequest struct{
    PolicyTypeName string
}

func NewGetClusteringV1PolicytypesRequest()*GetClusteringV1PolicytypesRequest{
    return &GetClusteringV1PolicytypesRequest{}
}

//response struct for the GetClusteringV1Policytypes
type GetClusteringV1PolicytypesResponse struct{
    GetResult policytypes.GetResult
}

func NewGetClusteringV1PolicytypesResponse(getResult policytypes.GetResult,)*GetClusteringV1PolicytypesResponse {
    return &GetClusteringV1PolicytypesResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetClusteringV1Policytypes(req *GetClusteringV1PolicytypesRequest)(*GetClusteringV1PolicytypesResponse){
    return NewGetClusteringV1PolicytypesResponse(policytypes.Get(oc.Client,req.PolicyTypeName, ))

}