package openstack

// Code generated by cloud manager.

import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/injectnetworkinfo"
)
//request struct for the InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfo
type InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoRequest struct{
    Id string
}

func NewInjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoRequest()*InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoRequest{
    return &InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoRequest{}
}

//response struct for the InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfo
type InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoResponse struct{
    InjectNetworkResult injectnetworkinfo.InjectNetworkResult
}

func NewInjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoResponse(injectNetworkResult injectnetworkinfo.InjectNetworkResult,)*InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoResponse {
    return &InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoResponse{
            InjectNetworkResult:injectNetworkResult,
    }
}

// action function
func (oc *OpenstackClient) InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfo(req *InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoRequest)(*InjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoResponse){
    return NewInjectNetworkInfoComputeV2ExtensionsInjectnetworkinfoResponse(injectnetworkinfo.InjectNetworkInfo(oc.Client,req.Id, ))

}