package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/rescueunrescue"
)
//request struct for the RescueComputeV2ExtensionsRescueunrescue
type RescueComputeV2ExtensionsRescueunrescueRequest struct{
    Id string
    Opts rescueunrescue.RescueOptsBuilder
}

func NewRescueComputeV2ExtensionsRescueunrescueRequest()*RescueComputeV2ExtensionsRescueunrescueRequest{
    return &RescueComputeV2ExtensionsRescueunrescueRequest{}
}

//response struct for the RescueComputeV2ExtensionsRescueunrescue
type RescueComputeV2ExtensionsRescueunrescueResponse struct{
    RescueResult rescueunrescue.RescueResult
}

func NewRescueComputeV2ExtensionsRescueunrescueResponse(rescueResult rescueunrescue.RescueResult,)*RescueComputeV2ExtensionsRescueunrescueResponse {
    return &RescueComputeV2ExtensionsRescueunrescueResponse{
            RescueResult:rescueResult,
    }
}

// action function
func (oc *OpenstackClient) RescueComputeV2ExtensionsRescueunrescue(request *RescueComputeV2ExtensionsRescueunrescueRequest)(*RescueComputeV2ExtensionsRescueunrescueResponse){
    return NewRescueComputeV2ExtensionsRescueunrescueResponse(rescueunrescue.Rescue(oc.client,request.Id,request.Opts, ))

}
//request struct for the UnrescueComputeV2ExtensionsRescueunrescue
type UnrescueComputeV2ExtensionsRescueunrescueRequest struct{
    Id string
}

func NewUnrescueComputeV2ExtensionsRescueunrescueRequest()*UnrescueComputeV2ExtensionsRescueunrescueRequest{
    return &UnrescueComputeV2ExtensionsRescueunrescueRequest{}
}

//response struct for the UnrescueComputeV2ExtensionsRescueunrescue
type UnrescueComputeV2ExtensionsRescueunrescueResponse struct{
    UnrescueResult rescueunrescue.UnrescueResult
}

func NewUnrescueComputeV2ExtensionsRescueunrescueResponse(unrescueResult rescueunrescue.UnrescueResult,)*UnrescueComputeV2ExtensionsRescueunrescueResponse {
    return &UnrescueComputeV2ExtensionsRescueunrescueResponse{
            UnrescueResult:unrescueResult,
    }
}

// action function
func (oc *OpenstackClient) UnrescueComputeV2ExtensionsRescueunrescue(request *UnrescueComputeV2ExtensionsRescueunrescueRequest)(*UnrescueComputeV2ExtensionsRescueunrescueResponse){
    return NewUnrescueComputeV2ExtensionsRescueunrescueResponse(rescueunrescue.Unrescue(oc.client,request.Id, ))

}