package openstack

// Code generated by cloud manager.

import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/evacuate"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/lockunlock"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/migrate"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/pauseunpause"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/rescueunrescue"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/resetnetwork"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/resetstate"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/shelveunshelve"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/startstop"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/suspendresume"
    "github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListComputeV2Servers
type ListComputeV2ServersRequest struct{
    Opts servers.ListOpts
}

func NewListComputeV2ServersRequest()*ListComputeV2ServersRequest{
    return &ListComputeV2ServersRequest{}
}

//response struct for the ListComputeV2Servers
type ListComputeV2ServersResponse struct{
    Pager pagination.Pager
}

func NewListComputeV2ServersResponse(pager pagination.Pager,)*ListComputeV2ServersResponse {
    return &ListComputeV2ServersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListComputeV2Servers(req *ListComputeV2ServersRequest)(*ListComputeV2ServersResponse){
    return NewListComputeV2ServersResponse(servers.List(oc.Client,req.Opts, ))

}
//request struct for the CreateComputeV2Servers
type CreateComputeV2ServersRequest struct{
    Opts servers.CreateOpts
}

func NewCreateComputeV2ServersRequest()*CreateComputeV2ServersRequest{
    return &CreateComputeV2ServersRequest{}
}

//response struct for the CreateComputeV2Servers
type CreateComputeV2ServersResponse struct{
    CreateResult servers.CreateResult
}

func NewCreateComputeV2ServersResponse(createResult servers.CreateResult,)*CreateComputeV2ServersResponse {
    return &CreateComputeV2ServersResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateComputeV2Servers(req *CreateComputeV2ServersRequest)(*CreateComputeV2ServersResponse){
    return NewCreateComputeV2ServersResponse(servers.Create(oc.Client,req.Opts, ))

}
//request struct for the DeleteComputeV2Servers
type DeleteComputeV2ServersRequest struct{
    Id string
}

func NewDeleteComputeV2ServersRequest()*DeleteComputeV2ServersRequest{
    return &DeleteComputeV2ServersRequest{}
}

//response struct for the DeleteComputeV2Servers
type DeleteComputeV2ServersResponse struct{
    DeleteResult servers.DeleteResult
}

func NewDeleteComputeV2ServersResponse(deleteResult servers.DeleteResult,)*DeleteComputeV2ServersResponse {
    return &DeleteComputeV2ServersResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteComputeV2Servers(req *DeleteComputeV2ServersRequest)(*DeleteComputeV2ServersResponse){
    return NewDeleteComputeV2ServersResponse(servers.Delete(oc.Client,req.Id, ))

}
//request struct for the ForceDeleteComputeV2Servers
type ForceDeleteComputeV2ServersRequest struct{
    Id string
}

func NewForceDeleteComputeV2ServersRequest()*ForceDeleteComputeV2ServersRequest{
    return &ForceDeleteComputeV2ServersRequest{}
}

//response struct for the ForceDeleteComputeV2Servers
type ForceDeleteComputeV2ServersResponse struct{
    ActionResult servers.ActionResult
}

func NewForceDeleteComputeV2ServersResponse(actionResult servers.ActionResult,)*ForceDeleteComputeV2ServersResponse {
    return &ForceDeleteComputeV2ServersResponse{
            ActionResult:actionResult,
    }
}

// action function
func (oc *OpenstackClient) ForceDeleteComputeV2Servers(req *ForceDeleteComputeV2ServersRequest)(*ForceDeleteComputeV2ServersResponse){
    return NewForceDeleteComputeV2ServersResponse(servers.ForceDelete(oc.Client,req.Id, ))

}
//request struct for the GetComputeV2Servers
type GetComputeV2ServersRequest struct{
    Id string
}

func NewGetComputeV2ServersRequest()*GetComputeV2ServersRequest{
    return &GetComputeV2ServersRequest{}
}

//response struct for the GetComputeV2Servers
type GetComputeV2ServersResponse struct{
    GetResult servers.GetResult
}

func NewGetComputeV2ServersResponse(getResult servers.GetResult,)*GetComputeV2ServersResponse {
    return &GetComputeV2ServersResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetComputeV2Servers(req *GetComputeV2ServersRequest)(*GetComputeV2ServersResponse){
    return NewGetComputeV2ServersResponse(servers.Get(oc.Client,req.Id, ))

}
//request struct for the UpdateComputeV2Servers
type UpdateComputeV2ServersRequest struct{
    Id string
    Opts servers.UpdateOpts
}

func NewUpdateComputeV2ServersRequest()*UpdateComputeV2ServersRequest{
    return &UpdateComputeV2ServersRequest{}
}

//response struct for the UpdateComputeV2Servers
type UpdateComputeV2ServersResponse struct{
    UpdateResult servers.UpdateResult
}

func NewUpdateComputeV2ServersResponse(updateResult servers.UpdateResult,)*UpdateComputeV2ServersResponse {
    return &UpdateComputeV2ServersResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateComputeV2Servers(req *UpdateComputeV2ServersRequest)(*UpdateComputeV2ServersResponse){
    return NewUpdateComputeV2ServersResponse(servers.Update(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ChangeAdminPasswordComputeV2Servers
type ChangeAdminPasswordComputeV2ServersRequest struct{
    Id string
    NewPassword string
}

func NewChangeAdminPasswordComputeV2ServersRequest()*ChangeAdminPasswordComputeV2ServersRequest{
    return &ChangeAdminPasswordComputeV2ServersRequest{}
}

//response struct for the ChangeAdminPasswordComputeV2Servers
type ChangeAdminPasswordComputeV2ServersResponse struct{
    ActionResult servers.ActionResult
}

func NewChangeAdminPasswordComputeV2ServersResponse(actionResult servers.ActionResult,)*ChangeAdminPasswordComputeV2ServersResponse {
    return &ChangeAdminPasswordComputeV2ServersResponse{
            ActionResult:actionResult,
    }
}

// action function
func (oc *OpenstackClient) ChangeAdminPasswordComputeV2Servers(req *ChangeAdminPasswordComputeV2ServersRequest)(*ChangeAdminPasswordComputeV2ServersResponse){
    return NewChangeAdminPasswordComputeV2ServersResponse(servers.ChangeAdminPassword(oc.Client,req.Id,req.NewPassword, ))

}
//request struct for the RebootComputeV2Servers
type RebootComputeV2ServersRequest struct{
    Id string
    Opts servers.RebootOpts
}

func NewRebootComputeV2ServersRequest()*RebootComputeV2ServersRequest{
    return &RebootComputeV2ServersRequest{}
}

//response struct for the RebootComputeV2Servers
type RebootComputeV2ServersResponse struct{
    ActionResult servers.ActionResult
}

func NewRebootComputeV2ServersResponse(actionResult servers.ActionResult,)*RebootComputeV2ServersResponse {
    return &RebootComputeV2ServersResponse{
            ActionResult:actionResult,
    }
}

// action function
func (oc *OpenstackClient) RebootComputeV2Servers(req *RebootComputeV2ServersRequest)(*RebootComputeV2ServersResponse){
    return NewRebootComputeV2ServersResponse(servers.Reboot(oc.Client,req.Id,req.Opts, ))

}
//request struct for the RebuildComputeV2Servers
type RebuildComputeV2ServersRequest struct{
    Id string
    Opts servers.RebuildOpts
}

func NewRebuildComputeV2ServersRequest()*RebuildComputeV2ServersRequest{
    return &RebuildComputeV2ServersRequest{}
}

//response struct for the RebuildComputeV2Servers
type RebuildComputeV2ServersResponse struct{
    RebuildResult servers.RebuildResult
}

func NewRebuildComputeV2ServersResponse(rebuildResult servers.RebuildResult,)*RebuildComputeV2ServersResponse {
    return &RebuildComputeV2ServersResponse{
            RebuildResult:rebuildResult,
    }
}

// action function
func (oc *OpenstackClient) RebuildComputeV2Servers(req *RebuildComputeV2ServersRequest)(*RebuildComputeV2ServersResponse){
    return NewRebuildComputeV2ServersResponse(servers.Rebuild(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ResizeComputeV2Servers
type ResizeComputeV2ServersRequest struct{
    Id string
    Opts servers.ResizeOpts
}

func NewResizeComputeV2ServersRequest()*ResizeComputeV2ServersRequest{
    return &ResizeComputeV2ServersRequest{}
}

//response struct for the ResizeComputeV2Servers
type ResizeComputeV2ServersResponse struct{
    ActionResult servers.ActionResult
}

func NewResizeComputeV2ServersResponse(actionResult servers.ActionResult,)*ResizeComputeV2ServersResponse {
    return &ResizeComputeV2ServersResponse{
            ActionResult:actionResult,
    }
}

// action function
func (oc *OpenstackClient) ResizeComputeV2Servers(req *ResizeComputeV2ServersRequest)(*ResizeComputeV2ServersResponse){
    return NewResizeComputeV2ServersResponse(servers.Resize(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ConfirmResizeComputeV2Servers
type ConfirmResizeComputeV2ServersRequest struct{
    Id string
}

func NewConfirmResizeComputeV2ServersRequest()*ConfirmResizeComputeV2ServersRequest{
    return &ConfirmResizeComputeV2ServersRequest{}
}

//response struct for the ConfirmResizeComputeV2Servers
type ConfirmResizeComputeV2ServersResponse struct{
    ActionResult servers.ActionResult
}

func NewConfirmResizeComputeV2ServersResponse(actionResult servers.ActionResult,)*ConfirmResizeComputeV2ServersResponse {
    return &ConfirmResizeComputeV2ServersResponse{
            ActionResult:actionResult,
    }
}

// action function
func (oc *OpenstackClient) ConfirmResizeComputeV2Servers(req *ConfirmResizeComputeV2ServersRequest)(*ConfirmResizeComputeV2ServersResponse){
    return NewConfirmResizeComputeV2ServersResponse(servers.ConfirmResize(oc.Client,req.Id, ))

}
//request struct for the RevertResizeComputeV2Servers
type RevertResizeComputeV2ServersRequest struct{
    Id string
}

func NewRevertResizeComputeV2ServersRequest()*RevertResizeComputeV2ServersRequest{
    return &RevertResizeComputeV2ServersRequest{}
}

//response struct for the RevertResizeComputeV2Servers
type RevertResizeComputeV2ServersResponse struct{
    ActionResult servers.ActionResult
}

func NewRevertResizeComputeV2ServersResponse(actionResult servers.ActionResult,)*RevertResizeComputeV2ServersResponse {
    return &RevertResizeComputeV2ServersResponse{
            ActionResult:actionResult,
    }
}

// action function
func (oc *OpenstackClient) RevertResizeComputeV2Servers(req *RevertResizeComputeV2ServersRequest)(*RevertResizeComputeV2ServersResponse){
    return NewRevertResizeComputeV2ServersResponse(servers.RevertResize(oc.Client,req.Id, ))

}
//request struct for the ResetMetadataComputeV2Servers
type ResetMetadataComputeV2ServersRequest struct{
    Id string
    Opts servers.MetadataOpts
}

func NewResetMetadataComputeV2ServersRequest()*ResetMetadataComputeV2ServersRequest{
    return &ResetMetadataComputeV2ServersRequest{}
}

//response struct for the ResetMetadataComputeV2Servers
type ResetMetadataComputeV2ServersResponse struct{
    ResetMetadataResult servers.ResetMetadataResult
}

func NewResetMetadataComputeV2ServersResponse(resetMetadataResult servers.ResetMetadataResult,)*ResetMetadataComputeV2ServersResponse {
    return &ResetMetadataComputeV2ServersResponse{
            ResetMetadataResult:resetMetadataResult,
    }
}

// action function
func (oc *OpenstackClient) ResetMetadataComputeV2Servers(req *ResetMetadataComputeV2ServersRequest)(*ResetMetadataComputeV2ServersResponse){
    return NewResetMetadataComputeV2ServersResponse(servers.ResetMetadata(oc.Client,req.Id,req.Opts, ))

}
//request struct for the MetadataComputeV2Servers
type MetadataComputeV2ServersRequest struct{
    Id string
}

func NewMetadataComputeV2ServersRequest()*MetadataComputeV2ServersRequest{
    return &MetadataComputeV2ServersRequest{}
}

//response struct for the MetadataComputeV2Servers
type MetadataComputeV2ServersResponse struct{
    GetMetadataResult servers.GetMetadataResult
}

func NewMetadataComputeV2ServersResponse(getMetadataResult servers.GetMetadataResult,)*MetadataComputeV2ServersResponse {
    return &MetadataComputeV2ServersResponse{
            GetMetadataResult:getMetadataResult,
    }
}

// action function
func (oc *OpenstackClient) MetadataComputeV2Servers(req *MetadataComputeV2ServersRequest)(*MetadataComputeV2ServersResponse){
    return NewMetadataComputeV2ServersResponse(servers.Metadata(oc.Client,req.Id, ))

}
//request struct for the UpdateMetadataComputeV2Servers
type UpdateMetadataComputeV2ServersRequest struct{
    Id string
    Opts servers.MetadataOpts
}

func NewUpdateMetadataComputeV2ServersRequest()*UpdateMetadataComputeV2ServersRequest{
    return &UpdateMetadataComputeV2ServersRequest{}
}

//response struct for the UpdateMetadataComputeV2Servers
type UpdateMetadataComputeV2ServersResponse struct{
    UpdateMetadataResult servers.UpdateMetadataResult
}

func NewUpdateMetadataComputeV2ServersResponse(updateMetadataResult servers.UpdateMetadataResult,)*UpdateMetadataComputeV2ServersResponse {
    return &UpdateMetadataComputeV2ServersResponse{
            UpdateMetadataResult:updateMetadataResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateMetadataComputeV2Servers(req *UpdateMetadataComputeV2ServersRequest)(*UpdateMetadataComputeV2ServersResponse){
    return NewUpdateMetadataComputeV2ServersResponse(servers.UpdateMetadata(oc.Client,req.Id,req.Opts, ))

}
//request struct for the CreateMetadatumComputeV2Servers
type CreateMetadatumComputeV2ServersRequest struct{
    Id string
    Opts servers.MetadatumOpts
}

func NewCreateMetadatumComputeV2ServersRequest()*CreateMetadatumComputeV2ServersRequest{
    return &CreateMetadatumComputeV2ServersRequest{}
}

//response struct for the CreateMetadatumComputeV2Servers
type CreateMetadatumComputeV2ServersResponse struct{
    CreateMetadatumResult servers.CreateMetadatumResult
}

func NewCreateMetadatumComputeV2ServersResponse(createMetadatumResult servers.CreateMetadatumResult,)*CreateMetadatumComputeV2ServersResponse {
    return &CreateMetadatumComputeV2ServersResponse{
            CreateMetadatumResult:createMetadatumResult,
    }
}

// action function
func (oc *OpenstackClient) CreateMetadatumComputeV2Servers(req *CreateMetadatumComputeV2ServersRequest)(*CreateMetadatumComputeV2ServersResponse){
    return NewCreateMetadatumComputeV2ServersResponse(servers.CreateMetadatum(oc.Client,req.Id,req.Opts, ))

}
//request struct for the MetadatumComputeV2Servers
type MetadatumComputeV2ServersRequest struct{
    Id string
    Key string
}

func NewMetadatumComputeV2ServersRequest()*MetadatumComputeV2ServersRequest{
    return &MetadatumComputeV2ServersRequest{}
}

//response struct for the MetadatumComputeV2Servers
type MetadatumComputeV2ServersResponse struct{
    GetMetadatumResult servers.GetMetadatumResult
}

func NewMetadatumComputeV2ServersResponse(getMetadatumResult servers.GetMetadatumResult,)*MetadatumComputeV2ServersResponse {
    return &MetadatumComputeV2ServersResponse{
            GetMetadatumResult:getMetadatumResult,
    }
}

// action function
func (oc *OpenstackClient) MetadatumComputeV2Servers(req *MetadatumComputeV2ServersRequest)(*MetadatumComputeV2ServersResponse){
    return NewMetadatumComputeV2ServersResponse(servers.Metadatum(oc.Client,req.Id,req.Key, ))

}
//request struct for the DeleteMetadatumComputeV2Servers
type DeleteMetadatumComputeV2ServersRequest struct{
    Id string
    Key string
}

func NewDeleteMetadatumComputeV2ServersRequest()*DeleteMetadatumComputeV2ServersRequest{
    return &DeleteMetadatumComputeV2ServersRequest{}
}

//response struct for the DeleteMetadatumComputeV2Servers
type DeleteMetadatumComputeV2ServersResponse struct{
    DeleteMetadatumResult servers.DeleteMetadatumResult
}

func NewDeleteMetadatumComputeV2ServersResponse(deleteMetadatumResult servers.DeleteMetadatumResult,)*DeleteMetadatumComputeV2ServersResponse {
    return &DeleteMetadatumComputeV2ServersResponse{
            DeleteMetadatumResult:deleteMetadatumResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteMetadatumComputeV2Servers(req *DeleteMetadatumComputeV2ServersRequest)(*DeleteMetadatumComputeV2ServersResponse){
    return NewDeleteMetadatumComputeV2ServersResponse(servers.DeleteMetadatum(oc.Client,req.Id,req.Key, ))

}
//request struct for the ListAddressesComputeV2Servers
type ListAddressesComputeV2ServersRequest struct{
    Id string
}

func NewListAddressesComputeV2ServersRequest()*ListAddressesComputeV2ServersRequest{
    return &ListAddressesComputeV2ServersRequest{}
}

//response struct for the ListAddressesComputeV2Servers
type ListAddressesComputeV2ServersResponse struct{
    Pager pagination.Pager
}

func NewListAddressesComputeV2ServersResponse(pager pagination.Pager,)*ListAddressesComputeV2ServersResponse {
    return &ListAddressesComputeV2ServersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListAddressesComputeV2Servers(req *ListAddressesComputeV2ServersRequest)(*ListAddressesComputeV2ServersResponse){
    return NewListAddressesComputeV2ServersResponse(servers.ListAddresses(oc.Client,req.Id, ))

}
//request struct for the ListAddressesByNetworkComputeV2Servers
type ListAddressesByNetworkComputeV2ServersRequest struct{
    Id string
    Network string
}

func NewListAddressesByNetworkComputeV2ServersRequest()*ListAddressesByNetworkComputeV2ServersRequest{
    return &ListAddressesByNetworkComputeV2ServersRequest{}
}

//response struct for the ListAddressesByNetworkComputeV2Servers
type ListAddressesByNetworkComputeV2ServersResponse struct{
    Pager pagination.Pager
}

func NewListAddressesByNetworkComputeV2ServersResponse(pager pagination.Pager,)*ListAddressesByNetworkComputeV2ServersResponse {
    return &ListAddressesByNetworkComputeV2ServersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListAddressesByNetworkComputeV2Servers(req *ListAddressesByNetworkComputeV2ServersRequest)(*ListAddressesByNetworkComputeV2ServersResponse){
    return NewListAddressesByNetworkComputeV2ServersResponse(servers.ListAddressesByNetwork(oc.Client,req.Id,req.Network, ))

}
//request struct for the CreateImageComputeV2Servers
type CreateImageComputeV2ServersRequest struct{
    Id string
    Opts servers.CreateImageOpts
}

func NewCreateImageComputeV2ServersRequest()*CreateImageComputeV2ServersRequest{
    return &CreateImageComputeV2ServersRequest{}
}

//response struct for the CreateImageComputeV2Servers
type CreateImageComputeV2ServersResponse struct{
    CreateImageResult servers.CreateImageResult
}

func NewCreateImageComputeV2ServersResponse(createImageResult servers.CreateImageResult,)*CreateImageComputeV2ServersResponse {
    return &CreateImageComputeV2ServersResponse{
            CreateImageResult:createImageResult,
    }
}

// action function
func (oc *OpenstackClient) CreateImageComputeV2Servers(req *CreateImageComputeV2ServersRequest)(*CreateImageComputeV2ServersResponse){
    return NewCreateImageComputeV2ServersResponse(servers.CreateImage(oc.Client,req.Id,req.Opts, ))

}
//request struct for the GetPasswordComputeV2Servers
type GetPasswordComputeV2ServersRequest struct{
    ServerId string
}

func NewGetPasswordComputeV2ServersRequest()*GetPasswordComputeV2ServersRequest{
    return &GetPasswordComputeV2ServersRequest{}
}

//response struct for the GetPasswordComputeV2Servers
type GetPasswordComputeV2ServersResponse struct{
    GetPasswordResult servers.GetPasswordResult
}

func NewGetPasswordComputeV2ServersResponse(getPasswordResult servers.GetPasswordResult,)*GetPasswordComputeV2ServersResponse {
    return &GetPasswordComputeV2ServersResponse{
            GetPasswordResult:getPasswordResult,
    }
}

// action function
func (oc *OpenstackClient) GetPasswordComputeV2Servers(req *GetPasswordComputeV2ServersRequest)(*GetPasswordComputeV2ServersResponse){
    return NewGetPasswordComputeV2ServersResponse(servers.GetPassword(oc.Client,req.ServerId, ))

}
//request struct for the ShowConsoleOutputComputeV2Servers
type ShowConsoleOutputComputeV2ServersRequest struct{
    Id string
    Opts servers.ShowConsoleOutputOpts
}

func NewShowConsoleOutputComputeV2ServersRequest()*ShowConsoleOutputComputeV2ServersRequest{
    return &ShowConsoleOutputComputeV2ServersRequest{}
}

//response struct for the ShowConsoleOutputComputeV2Servers
type ShowConsoleOutputComputeV2ServersResponse struct{
    ShowConsoleOutputResult servers.ShowConsoleOutputResult
}

func NewShowConsoleOutputComputeV2ServersResponse(showConsoleOutputResult servers.ShowConsoleOutputResult,)*ShowConsoleOutputComputeV2ServersResponse {
    return &ShowConsoleOutputComputeV2ServersResponse{
            ShowConsoleOutputResult:showConsoleOutputResult,
    }
}

// action function
func (oc *OpenstackClient) ShowConsoleOutputComputeV2Servers(req *ShowConsoleOutputComputeV2ServersRequest)(*ShowConsoleOutputComputeV2ServersResponse){
    return NewShowConsoleOutputComputeV2ServersResponse(servers.ShowConsoleOutput(oc.Client,req.Id,req.Opts, ))

}
//request struct for the EvacuateComputeV2Servers
type EvacuateComputeV2ServersRequest struct{
    Id string
    Opts evacuate.EvacuateOpts
}

func NewEvacuateComputeV2ServersRequest()*EvacuateComputeV2ServersRequest{
    return &EvacuateComputeV2ServersRequest{}
}

//response struct for the EvacuateComputeV2Servers
type EvacuateComputeV2ServersResponse struct{
    EvacuateResult evacuate.EvacuateResult
}

func NewEvacuateComputeV2ServersResponse(evacuateResult evacuate.EvacuateResult,)*EvacuateComputeV2ServersResponse {
    return &EvacuateComputeV2ServersResponse{
            EvacuateResult:evacuateResult,
    }
}

// action function
func (oc *OpenstackClient) EvacuateComputeV2Servers(req *EvacuateComputeV2ServersRequest)(*EvacuateComputeV2ServersResponse){
    return NewEvacuateComputeV2ServersResponse(evacuate.Evacuate(oc.Client,req.Id,req.Opts, ))

}
//request struct for the SuspendComputeV2Servers
type SuspendComputeV2ServersRequest struct{
    Id string
}

func NewSuspendComputeV2ServersRequest()*SuspendComputeV2ServersRequest{
    return &SuspendComputeV2ServersRequest{}
}

//response struct for the SuspendComputeV2Servers
type SuspendComputeV2ServersResponse struct{
    SuspendResult suspendresume.SuspendResult
}

func NewSuspendComputeV2ServersResponse(suspendResult suspendresume.SuspendResult,)*SuspendComputeV2ServersResponse {
    return &SuspendComputeV2ServersResponse{
            SuspendResult:suspendResult,
    }
}

// action function
func (oc *OpenstackClient) SuspendComputeV2Servers(req *SuspendComputeV2ServersRequest)(*SuspendComputeV2ServersResponse){
    return NewSuspendComputeV2ServersResponse(suspendresume.Suspend(oc.Client,req.Id, ))

}
//request struct for the ResumeComputeV2Servers
type ResumeComputeV2ServersRequest struct{
    Id string
}

func NewResumeComputeV2ServersRequest()*ResumeComputeV2ServersRequest{
    return &ResumeComputeV2ServersRequest{}
}

//response struct for the ResumeComputeV2Servers
type ResumeComputeV2ServersResponse struct{
    UnsuspendResult suspendresume.UnsuspendResult
}

func NewResumeComputeV2ServersResponse(unsuspendResult suspendresume.UnsuspendResult,)*ResumeComputeV2ServersResponse {
    return &ResumeComputeV2ServersResponse{
            UnsuspendResult:unsuspendResult,
    }
}

// action function
func (oc *OpenstackClient) ResumeComputeV2Servers(req *ResumeComputeV2ServersRequest)(*ResumeComputeV2ServersResponse){
    return NewResumeComputeV2ServersResponse(suspendresume.Resume(oc.Client,req.Id, ))

}
//request struct for the StartComputeV2Servers
type StartComputeV2ServersRequest struct{
    Id string
}

func NewStartComputeV2ServersRequest()*StartComputeV2ServersRequest{
    return &StartComputeV2ServersRequest{}
}

//response struct for the StartComputeV2Servers
type StartComputeV2ServersResponse struct{
    StartResult startstop.StartResult
}

func NewStartComputeV2ServersResponse(startResult startstop.StartResult,)*StartComputeV2ServersResponse {
    return &StartComputeV2ServersResponse{
            StartResult:startResult,
    }
}

// action function
func (oc *OpenstackClient) StartComputeV2Servers(req *StartComputeV2ServersRequest)(*StartComputeV2ServersResponse){
    return NewStartComputeV2ServersResponse(startstop.Start(oc.Client,req.Id, ))

}
//request struct for the StopComputeV2Servers
type StopComputeV2ServersRequest struct{
    Id string
}

func NewStopComputeV2ServersRequest()*StopComputeV2ServersRequest{
    return &StopComputeV2ServersRequest{}
}

//response struct for the StopComputeV2Servers
type StopComputeV2ServersResponse struct{
    StopResult startstop.StopResult
}

func NewStopComputeV2ServersResponse(stopResult startstop.StopResult,)*StopComputeV2ServersResponse {
    return &StopComputeV2ServersResponse{
            StopResult:stopResult,
    }
}

// action function
func (oc *OpenstackClient) StopComputeV2Servers(req *StopComputeV2ServersRequest)(*StopComputeV2ServersResponse){
    return NewStopComputeV2ServersResponse(startstop.Stop(oc.Client,req.Id, ))

}
//request struct for the ShelveComputeV2Servers
type ShelveComputeV2ServersRequest struct{
    Id string
}

func NewShelveComputeV2ServersRequest()*ShelveComputeV2ServersRequest{
    return &ShelveComputeV2ServersRequest{}
}

//response struct for the ShelveComputeV2Servers
type ShelveComputeV2ServersResponse struct{
    ShelveResult shelveunshelve.ShelveResult
}

func NewShelveComputeV2ServersResponse(shelveResult shelveunshelve.ShelveResult,)*ShelveComputeV2ServersResponse {
    return &ShelveComputeV2ServersResponse{
            ShelveResult:shelveResult,
    }
}

// action function
func (oc *OpenstackClient) ShelveComputeV2Servers(req *ShelveComputeV2ServersRequest)(*ShelveComputeV2ServersResponse){
    return NewShelveComputeV2ServersResponse(shelveunshelve.Shelve(oc.Client,req.Id, ))

}
//request struct for the ShelveOffloadComputeV2Servers
type ShelveOffloadComputeV2ServersRequest struct{
    Id string
}

func NewShelveOffloadComputeV2ServersRequest()*ShelveOffloadComputeV2ServersRequest{
    return &ShelveOffloadComputeV2ServersRequest{}
}

//response struct for the ShelveOffloadComputeV2Servers
type ShelveOffloadComputeV2ServersResponse struct{
    ShelveOffloadResult shelveunshelve.ShelveOffloadResult
}

func NewShelveOffloadComputeV2ServersResponse(shelveOffloadResult shelveunshelve.ShelveOffloadResult,)*ShelveOffloadComputeV2ServersResponse {
    return &ShelveOffloadComputeV2ServersResponse{
            ShelveOffloadResult:shelveOffloadResult,
    }
}

// action function
func (oc *OpenstackClient) ShelveOffloadComputeV2Servers(req *ShelveOffloadComputeV2ServersRequest)(*ShelveOffloadComputeV2ServersResponse){
    return NewShelveOffloadComputeV2ServersResponse(shelveunshelve.ShelveOffload(oc.Client,req.Id, ))

}
//request struct for the UnshelveComputeV2Servers
type UnshelveComputeV2ServersRequest struct{
    Id string
    Opts shelveunshelve.UnshelveOpts
}

func NewUnshelveComputeV2ServersRequest()*UnshelveComputeV2ServersRequest{
    return &UnshelveComputeV2ServersRequest{}
}

//response struct for the UnshelveComputeV2Servers
type UnshelveComputeV2ServersResponse struct{
    UnshelveResult shelveunshelve.UnshelveResult
}

func NewUnshelveComputeV2ServersResponse(unshelveResult shelveunshelve.UnshelveResult,)*UnshelveComputeV2ServersResponse {
    return &UnshelveComputeV2ServersResponse{
            UnshelveResult:unshelveResult,
    }
}

// action function
func (oc *OpenstackClient) UnshelveComputeV2Servers(req *UnshelveComputeV2ServersRequest)(*UnshelveComputeV2ServersResponse){
    return NewUnshelveComputeV2ServersResponse(shelveunshelve.Unshelve(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ResetStateComputeV2Servers
type ResetStateComputeV2ServersRequest struct{
    Id string
    State resetstate.ServerState
}

func NewResetStateComputeV2ServersRequest()*ResetStateComputeV2ServersRequest{
    return &ResetStateComputeV2ServersRequest{}
}

//response struct for the ResetStateComputeV2Servers
type ResetStateComputeV2ServersResponse struct{
    ResetResult resetstate.ResetResult
}

func NewResetStateComputeV2ServersResponse(resetResult resetstate.ResetResult,)*ResetStateComputeV2ServersResponse {
    return &ResetStateComputeV2ServersResponse{
            ResetResult:resetResult,
    }
}

// action function
func (oc *OpenstackClient) ResetStateComputeV2Servers(req *ResetStateComputeV2ServersRequest)(*ResetStateComputeV2ServersResponse){
    return NewResetStateComputeV2ServersResponse(resetstate.ResetState(oc.Client,req.Id,req.State, ))

}
//request struct for the ResetNetworkComputeV2Servers
type ResetNetworkComputeV2ServersRequest struct{
    Id string
}

func NewResetNetworkComputeV2ServersRequest()*ResetNetworkComputeV2ServersRequest{
    return &ResetNetworkComputeV2ServersRequest{}
}

//response struct for the ResetNetworkComputeV2Servers
type ResetNetworkComputeV2ServersResponse struct{
    ResetResult resetnetwork.ResetResult
}

func NewResetNetworkComputeV2ServersResponse(resetResult resetnetwork.ResetResult,)*ResetNetworkComputeV2ServersResponse {
    return &ResetNetworkComputeV2ServersResponse{
            ResetResult:resetResult,
    }
}

// action function
func (oc *OpenstackClient) ResetNetworkComputeV2Servers(req *ResetNetworkComputeV2ServersRequest)(*ResetNetworkComputeV2ServersResponse){
    return NewResetNetworkComputeV2ServersResponse(resetnetwork.ResetNetwork(oc.Client,req.Id, ))

}
//request struct for the RescueComputeV2Servers
type RescueComputeV2ServersRequest struct{
    Id string
    Opts rescueunrescue.RescueOpts
}

func NewRescueComputeV2ServersRequest()*RescueComputeV2ServersRequest{
    return &RescueComputeV2ServersRequest{}
}

//response struct for the RescueComputeV2Servers
type RescueComputeV2ServersResponse struct{
    RescueResult rescueunrescue.RescueResult
}

func NewRescueComputeV2ServersResponse(rescueResult rescueunrescue.RescueResult,)*RescueComputeV2ServersResponse {
    return &RescueComputeV2ServersResponse{
            RescueResult:rescueResult,
    }
}

// action function
func (oc *OpenstackClient) RescueComputeV2Servers(req *RescueComputeV2ServersRequest)(*RescueComputeV2ServersResponse){
    return NewRescueComputeV2ServersResponse(rescueunrescue.Rescue(oc.Client,req.Id,req.Opts, ))

}
//request struct for the UnrescueComputeV2Servers
type UnrescueComputeV2ServersRequest struct{
    Id string
}

func NewUnrescueComputeV2ServersRequest()*UnrescueComputeV2ServersRequest{
    return &UnrescueComputeV2ServersRequest{}
}

//response struct for the UnrescueComputeV2Servers
type UnrescueComputeV2ServersResponse struct{
    UnrescueResult rescueunrescue.UnrescueResult
}

func NewUnrescueComputeV2ServersResponse(unrescueResult rescueunrescue.UnrescueResult,)*UnrescueComputeV2ServersResponse {
    return &UnrescueComputeV2ServersResponse{
            UnrescueResult:unrescueResult,
    }
}

// action function
func (oc *OpenstackClient) UnrescueComputeV2Servers(req *UnrescueComputeV2ServersRequest)(*UnrescueComputeV2ServersResponse){
    return NewUnrescueComputeV2ServersResponse(rescueunrescue.Unrescue(oc.Client,req.Id, ))

}
//request struct for the PauseComputeV2Servers
type PauseComputeV2ServersRequest struct{
    Id string
}

func NewPauseComputeV2ServersRequest()*PauseComputeV2ServersRequest{
    return &PauseComputeV2ServersRequest{}
}

//response struct for the PauseComputeV2Servers
type PauseComputeV2ServersResponse struct{
    PauseResult pauseunpause.PauseResult
}

func NewPauseComputeV2ServersResponse(pauseResult pauseunpause.PauseResult,)*PauseComputeV2ServersResponse {
    return &PauseComputeV2ServersResponse{
            PauseResult:pauseResult,
    }
}

// action function
func (oc *OpenstackClient) PauseComputeV2Servers(req *PauseComputeV2ServersRequest)(*PauseComputeV2ServersResponse){
    return NewPauseComputeV2ServersResponse(pauseunpause.Pause(oc.Client,req.Id, ))

}
//request struct for the UnpauseComputeV2Servers
type UnpauseComputeV2ServersRequest struct{
    Id string
}

func NewUnpauseComputeV2ServersRequest()*UnpauseComputeV2ServersRequest{
    return &UnpauseComputeV2ServersRequest{}
}

//response struct for the UnpauseComputeV2Servers
type UnpauseComputeV2ServersResponse struct{
    UnpauseResult pauseunpause.UnpauseResult
}

func NewUnpauseComputeV2ServersResponse(unpauseResult pauseunpause.UnpauseResult,)*UnpauseComputeV2ServersResponse {
    return &UnpauseComputeV2ServersResponse{
            UnpauseResult:unpauseResult,
    }
}

// action function
func (oc *OpenstackClient) UnpauseComputeV2Servers(req *UnpauseComputeV2ServersRequest)(*UnpauseComputeV2ServersResponse){
    return NewUnpauseComputeV2ServersResponse(pauseunpause.Unpause(oc.Client,req.Id, ))

}
//request struct for the LockComputeV2Servers
type LockComputeV2ServersRequest struct{
    Id string
}

func NewLockComputeV2ServersRequest()*LockComputeV2ServersRequest{
    return &LockComputeV2ServersRequest{}
}

//response struct for the LockComputeV2Servers
type LockComputeV2ServersResponse struct{
    LockResult lockunlock.LockResult
}

func NewLockComputeV2ServersResponse(lockResult lockunlock.LockResult,)*LockComputeV2ServersResponse {
    return &LockComputeV2ServersResponse{
            LockResult:lockResult,
    }
}

// action function
func (oc *OpenstackClient) LockComputeV2Servers(req *LockComputeV2ServersRequest)(*LockComputeV2ServersResponse){
    return NewLockComputeV2ServersResponse(lockunlock.Lock(oc.Client,req.Id, ))

}
//request struct for the UnlockComputeV2Servers
type UnlockComputeV2ServersRequest struct{
    Id string
}

func NewUnlockComputeV2ServersRequest()*UnlockComputeV2ServersRequest{
    return &UnlockComputeV2ServersRequest{}
}

//response struct for the UnlockComputeV2Servers
type UnlockComputeV2ServersResponse struct{
    UnlockResult lockunlock.UnlockResult
}

func NewUnlockComputeV2ServersResponse(unlockResult lockunlock.UnlockResult,)*UnlockComputeV2ServersResponse {
    return &UnlockComputeV2ServersResponse{
            UnlockResult:unlockResult,
    }
}

// action function
func (oc *OpenstackClient) UnlockComputeV2Servers(req *UnlockComputeV2ServersRequest)(*UnlockComputeV2ServersResponse){
    return NewUnlockComputeV2ServersResponse(lockunlock.Unlock(oc.Client,req.Id, ))

}
//request struct for the MigrateComputeV2Servers
type MigrateComputeV2ServersRequest struct{
    Id string
}

func NewMigrateComputeV2ServersRequest()*MigrateComputeV2ServersRequest{
    return &MigrateComputeV2ServersRequest{}
}

//response struct for the MigrateComputeV2Servers
type MigrateComputeV2ServersResponse struct{
    MigrateResult migrate.MigrateResult
}

func NewMigrateComputeV2ServersResponse(migrateResult migrate.MigrateResult,)*MigrateComputeV2ServersResponse {
    return &MigrateComputeV2ServersResponse{
            MigrateResult:migrateResult,
    }
}

// action function
func (oc *OpenstackClient) MigrateComputeV2Servers(req *MigrateComputeV2ServersRequest)(*MigrateComputeV2ServersResponse){
    return NewMigrateComputeV2ServersResponse(migrate.Migrate(oc.Client,req.Id, ))

}
//request struct for the LiveMigrateComputeV2Servers
type LiveMigrateComputeV2ServersRequest struct{
    Id string
    Opts migrate.LiveMigrateOpts
}

func NewLiveMigrateComputeV2ServersRequest()*LiveMigrateComputeV2ServersRequest{
    return &LiveMigrateComputeV2ServersRequest{}
}

//response struct for the LiveMigrateComputeV2Servers
type LiveMigrateComputeV2ServersResponse struct{
    MigrateResult migrate.MigrateResult
}

func NewLiveMigrateComputeV2ServersResponse(migrateResult migrate.MigrateResult,)*LiveMigrateComputeV2ServersResponse {
    return &LiveMigrateComputeV2ServersResponse{
            MigrateResult:migrateResult,
    }
}

// action function
func (oc *OpenstackClient) LiveMigrateComputeV2Servers(req *LiveMigrateComputeV2ServersRequest)(*LiveMigrateComputeV2ServersResponse){
    return NewLiveMigrateComputeV2ServersResponse(migrate.LiveMigrate(oc.Client,req.Id,req.Opts, ))

}