package openstack

// Code generated by cloud manager.

import (
	"github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/pauseunpause"
)

// request struct for the PauseComputeV2ExtensionsPauseunpause
type PauseComputeV2ExtensionsPauseunpauseRequest struct {
	Id string
}

func NewPauseComputeV2ExtensionsPauseunpauseRequest() *PauseComputeV2ExtensionsPauseunpauseRequest {
	return &PauseComputeV2ExtensionsPauseunpauseRequest{}
}

// response struct for the PauseComputeV2ExtensionsPauseunpause
type PauseComputeV2ExtensionsPauseunpauseResponse struct {
	PauseResult pauseunpause.PauseResult
}

func NewPauseComputeV2ExtensionsPauseunpauseResponse(pauseResult pauseunpause.PauseResult) *PauseComputeV2ExtensionsPauseunpauseResponse {
	return &PauseComputeV2ExtensionsPauseunpauseResponse{
		PauseResult: pauseResult,
	}
}

// action function
func (oc *OpenstackClient) PauseComputeV2ExtensionsPauseunpause(req *PauseComputeV2ExtensionsPauseunpauseRequest) *PauseComputeV2ExtensionsPauseunpauseResponse {
	return NewPauseComputeV2ExtensionsPauseunpauseResponse(pauseunpause.Pause(oc.Client, req.Id))

}

// request struct for the UnpauseComputeV2ExtensionsPauseunpause
type UnpauseComputeV2ExtensionsPauseunpauseRequest struct {
	Id string
}

func NewUnpauseComputeV2ExtensionsPauseunpauseRequest() *UnpauseComputeV2ExtensionsPauseunpauseRequest {
	return &UnpauseComputeV2ExtensionsPauseunpauseRequest{}
}

// response struct for the UnpauseComputeV2ExtensionsPauseunpause
type UnpauseComputeV2ExtensionsPauseunpauseResponse struct {
	UnpauseResult pauseunpause.UnpauseResult
}

func NewUnpauseComputeV2ExtensionsPauseunpauseResponse(unpauseResult pauseunpause.UnpauseResult) *UnpauseComputeV2ExtensionsPauseunpauseResponse {
	return &UnpauseComputeV2ExtensionsPauseunpauseResponse{
		UnpauseResult: unpauseResult,
	}
}

// action function
func (oc *OpenstackClient) UnpauseComputeV2ExtensionsPauseunpause(req *UnpauseComputeV2ExtensionsPauseunpauseRequest) *UnpauseComputeV2ExtensionsPauseunpauseResponse {
	return NewUnpauseComputeV2ExtensionsPauseunpauseResponse(pauseunpause.Unpause(oc.Client, req.Id))

}
