package openstack

// Code generated by cloud manager.

import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/evacuate"
)
//request struct for the EvacuateComputeV2ExtensionsEvacuate
type EvacuateComputeV2ExtensionsEvacuateRequest struct{
    Id string
    Opts evacuate.EvacuateOpts
}

func NewEvacuateComputeV2ExtensionsEvacuateRequest()*EvacuateComputeV2ExtensionsEvacuateRequest{
    return &EvacuateComputeV2ExtensionsEvacuateRequest{}
}

//response struct for the EvacuateComputeV2ExtensionsEvacuate
type EvacuateComputeV2ExtensionsEvacuateResponse struct{
    EvacuateResult evacuate.EvacuateResult
}

func NewEvacuateComputeV2ExtensionsEvacuateResponse(evacuateResult evacuate.EvacuateResult,)*EvacuateComputeV2ExtensionsEvacuateResponse {
    return &EvacuateComputeV2ExtensionsEvacuateResponse{
            EvacuateResult:evacuateResult,
    }
}

// action function
func (oc *OpenstackClient) EvacuateComputeV2ExtensionsEvacuate(req *EvacuateComputeV2ExtensionsEvacuateRequest)(*EvacuateComputeV2ExtensionsEvacuateResponse){
    return NewEvacuateComputeV2ExtensionsEvacuateResponse(evacuate.Evacuate(oc.Client,req.Id,req.Opts, ))

}