package openstack

// Code generated by cloud manager.

import (
    "github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateContainerinfraV1Clusters
type CreateContainerinfraV1ClustersRequest struct{
    Opts clusters.CreateOpts
}

func NewCreateContainerinfraV1ClustersRequest()*CreateContainerinfraV1ClustersRequest{
    return &CreateContainerinfraV1ClustersRequest{}
}

//response struct for the CreateContainerinfraV1Clusters
type CreateContainerinfraV1ClustersResponse struct{
    CreateResult clusters.CreateResult
}

func NewCreateContainerinfraV1ClustersResponse(createResult clusters.CreateResult,)*CreateContainerinfraV1ClustersResponse {
    return &CreateContainerinfraV1ClustersResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateContainerinfraV1Clusters(req *CreateContainerinfraV1ClustersRequest)(*CreateContainerinfraV1ClustersResponse){
    return NewCreateContainerinfraV1ClustersResponse(clusters.Create(oc.Client,req.Opts, ))

}
//request struct for the GetContainerinfraV1Clusters
type GetContainerinfraV1ClustersRequest struct{
    Id string
}

func NewGetContainerinfraV1ClustersRequest()*GetContainerinfraV1ClustersRequest{
    return &GetContainerinfraV1ClustersRequest{}
}

//response struct for the GetContainerinfraV1Clusters
type GetContainerinfraV1ClustersResponse struct{
    GetResult clusters.GetResult
}

func NewGetContainerinfraV1ClustersResponse(getResult clusters.GetResult,)*GetContainerinfraV1ClustersResponse {
    return &GetContainerinfraV1ClustersResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetContainerinfraV1Clusters(req *GetContainerinfraV1ClustersRequest)(*GetContainerinfraV1ClustersResponse){
    return NewGetContainerinfraV1ClustersResponse(clusters.Get(oc.Client,req.Id, ))

}
//request struct for the DeleteContainerinfraV1Clusters
type DeleteContainerinfraV1ClustersRequest struct{
    Id string
}

func NewDeleteContainerinfraV1ClustersRequest()*DeleteContainerinfraV1ClustersRequest{
    return &DeleteContainerinfraV1ClustersRequest{}
}

//response struct for the DeleteContainerinfraV1Clusters
type DeleteContainerinfraV1ClustersResponse struct{
    DeleteResult clusters.DeleteResult
}

func NewDeleteContainerinfraV1ClustersResponse(deleteResult clusters.DeleteResult,)*DeleteContainerinfraV1ClustersResponse {
    return &DeleteContainerinfraV1ClustersResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteContainerinfraV1Clusters(req *DeleteContainerinfraV1ClustersRequest)(*DeleteContainerinfraV1ClustersResponse){
    return NewDeleteContainerinfraV1ClustersResponse(clusters.Delete(oc.Client,req.Id, ))

}
//request struct for the ListContainerinfraV1Clusters
type ListContainerinfraV1ClustersRequest struct{
    Opts clusters.ListOpts
}

func NewListContainerinfraV1ClustersRequest()*ListContainerinfraV1ClustersRequest{
    return &ListContainerinfraV1ClustersRequest{}
}

//response struct for the ListContainerinfraV1Clusters
type ListContainerinfraV1ClustersResponse struct{
    Pager pagination.Pager
}

func NewListContainerinfraV1ClustersResponse(pager pagination.Pager,)*ListContainerinfraV1ClustersResponse {
    return &ListContainerinfraV1ClustersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListContainerinfraV1Clusters(req *ListContainerinfraV1ClustersRequest)(*ListContainerinfraV1ClustersResponse){
    return NewListContainerinfraV1ClustersResponse(clusters.List(oc.Client,req.Opts, ))

}
//request struct for the ListDetailContainerinfraV1Clusters
type ListDetailContainerinfraV1ClustersRequest struct{
    Opts clusters.ListOpts
}

func NewListDetailContainerinfraV1ClustersRequest()*ListDetailContainerinfraV1ClustersRequest{
    return &ListDetailContainerinfraV1ClustersRequest{}
}

//response struct for the ListDetailContainerinfraV1Clusters
type ListDetailContainerinfraV1ClustersResponse struct{
    Pager pagination.Pager
}

func NewListDetailContainerinfraV1ClustersResponse(pager pagination.Pager,)*ListDetailContainerinfraV1ClustersResponse {
    return &ListDetailContainerinfraV1ClustersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListDetailContainerinfraV1Clusters(req *ListDetailContainerinfraV1ClustersRequest)(*ListDetailContainerinfraV1ClustersResponse){
    return NewListDetailContainerinfraV1ClustersResponse(clusters.ListDetail(oc.Client,req.Opts, ))

}
//request struct for the UpgradeContainerinfraV1Clusters
type UpgradeContainerinfraV1ClustersRequest struct{
    Id string
    Opts clusters.UpgradeOpts
}

func NewUpgradeContainerinfraV1ClustersRequest()*UpgradeContainerinfraV1ClustersRequest{
    return &UpgradeContainerinfraV1ClustersRequest{}
}

//response struct for the UpgradeContainerinfraV1Clusters
type UpgradeContainerinfraV1ClustersResponse struct{
    UpgradeResult clusters.UpgradeResult
}

func NewUpgradeContainerinfraV1ClustersResponse(upgradeResult clusters.UpgradeResult,)*UpgradeContainerinfraV1ClustersResponse {
    return &UpgradeContainerinfraV1ClustersResponse{
            UpgradeResult:upgradeResult,
    }
}

// action function
func (oc *OpenstackClient) UpgradeContainerinfraV1Clusters(req *UpgradeContainerinfraV1ClustersRequest)(*UpgradeContainerinfraV1ClustersResponse){
    return NewUpgradeContainerinfraV1ClustersResponse(clusters.Upgrade(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ResizeContainerinfraV1Clusters
type ResizeContainerinfraV1ClustersRequest struct{
    Id string
    Opts clusters.ResizeOpts
}

func NewResizeContainerinfraV1ClustersRequest()*ResizeContainerinfraV1ClustersRequest{
    return &ResizeContainerinfraV1ClustersRequest{}
}

//response struct for the ResizeContainerinfraV1Clusters
type ResizeContainerinfraV1ClustersResponse struct{
    ResizeResult clusters.ResizeResult
}

func NewResizeContainerinfraV1ClustersResponse(resizeResult clusters.ResizeResult,)*ResizeContainerinfraV1ClustersResponse {
    return &ResizeContainerinfraV1ClustersResponse{
            ResizeResult:resizeResult,
    }
}

// action function
func (oc *OpenstackClient) ResizeContainerinfraV1Clusters(req *ResizeContainerinfraV1ClustersRequest)(*ResizeContainerinfraV1ClustersResponse){
    return NewResizeContainerinfraV1ClustersResponse(clusters.Resize(oc.Client,req.Id,req.Opts, ))

}