package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/container/v1/capsules"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the GetContainerV1Capsules
type GetContainerV1CapsulesRequest struct{
    Id string
}

func NewGetContainerV1CapsulesRequest()*GetContainerV1CapsulesRequest{
    return &GetContainerV1CapsulesRequest{}
}

//response struct for the GetContainerV1Capsules
type GetContainerV1CapsulesResponse struct{
    GetResult capsules.GetResult
}

func NewGetContainerV1CapsulesResponse(getResult capsules.GetResult,)*GetContainerV1CapsulesResponse {
    return &GetContainerV1CapsulesResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetContainerV1Capsules(req *GetContainerV1CapsulesRequest)(*GetContainerV1CapsulesResponse){
    return NewGetContainerV1CapsulesResponse(capsules.Get(oc.Client,req.Id, ))

}
//request struct for the CreateContainerV1Capsules
type CreateContainerV1CapsulesRequest struct{
    Opts capsules.CreateOpts
}

func NewCreateContainerV1CapsulesRequest()*CreateContainerV1CapsulesRequest{
    return &CreateContainerV1CapsulesRequest{}
}

//response struct for the CreateContainerV1Capsules
type CreateContainerV1CapsulesResponse struct{
    CreateResult capsules.CreateResult
}

func NewCreateContainerV1CapsulesResponse(createResult capsules.CreateResult,)*CreateContainerV1CapsulesResponse {
    return &CreateContainerV1CapsulesResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateContainerV1Capsules(req *CreateContainerV1CapsulesRequest)(*CreateContainerV1CapsulesResponse){
    return NewCreateContainerV1CapsulesResponse(capsules.Create(oc.Client,req.Opts, ))

}
//request struct for the ListContainerV1Capsules
type ListContainerV1CapsulesRequest struct{
    Opts capsules.ListOpts
}

func NewListContainerV1CapsulesRequest()*ListContainerV1CapsulesRequest{
    return &ListContainerV1CapsulesRequest{}
}

//response struct for the ListContainerV1Capsules
type ListContainerV1CapsulesResponse struct{
    Pager pagination.Pager
}

func NewListContainerV1CapsulesResponse(pager pagination.Pager,)*ListContainerV1CapsulesResponse {
    return &ListContainerV1CapsulesResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListContainerV1Capsules(req *ListContainerV1CapsulesRequest)(*ListContainerV1CapsulesResponse){
    return NewListContainerV1CapsulesResponse(capsules.List(oc.Client,req.Opts, ))

}
//request struct for the DeleteContainerV1Capsules
type DeleteContainerV1CapsulesRequest struct{
    Id string
}

func NewDeleteContainerV1CapsulesRequest()*DeleteContainerV1CapsulesRequest{
    return &DeleteContainerV1CapsulesRequest{}
}

//response struct for the DeleteContainerV1Capsules
type DeleteContainerV1CapsulesResponse struct{
    DeleteResult capsules.DeleteResult
}

func NewDeleteContainerV1CapsulesResponse(deleteResult capsules.DeleteResult,)*DeleteContainerV1CapsulesResponse {
    return &DeleteContainerV1CapsulesResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteContainerV1Capsules(req *DeleteContainerV1CapsulesRequest)(*DeleteContainerV1CapsulesResponse){
    return NewDeleteContainerV1CapsulesResponse(capsules.Delete(oc.Client,req.Id, ))

}