package openstack

// Code generated by cloud manager.

import (
	"github.com/gophercloud/gophercloud/openstack/containerinfra/v1/certificates"
)

// request struct for the GetContainerinfraV1Certificates
type GetContainerinfraV1CertificatesRequest struct {
	ClusterID string
}

func NewGetContainerinfraV1CertificatesRequest() *GetContainerinfraV1CertificatesRequest {
	return &GetContainerinfraV1CertificatesRequest{}
}

// response struct for the GetContainerinfraV1Certificates
type GetContainerinfraV1CertificatesResponse struct {
	GetResult certificates.GetResult
}

func NewGetContainerinfraV1CertificatesResponse(getResult certificates.GetResult) *GetContainerinfraV1CertificatesResponse {
	return &GetContainerinfraV1CertificatesResponse{
		GetResult: getResult,
	}
}

// action function
func (oc *OpenstackClient) GetContainerinfraV1Certificates(req *GetContainerinfraV1CertificatesRequest) *GetContainerinfraV1CertificatesResponse {
	return NewGetContainerinfraV1CertificatesResponse(certificates.Get(oc.Client, req.ClusterID))

}

// request struct for the CreateContainerinfraV1Certificates
type CreateContainerinfraV1CertificatesRequest struct {
	Opts certificates.CreateOpts
}

func NewCreateContainerinfraV1CertificatesRequest() *CreateContainerinfraV1CertificatesRequest {
	return &CreateContainerinfraV1CertificatesRequest{}
}

// response struct for the CreateContainerinfraV1Certificates
type CreateContainerinfraV1CertificatesResponse struct {
	CreateResult certificates.CreateResult
}

func NewCreateContainerinfraV1CertificatesResponse(createResult certificates.CreateResult) *CreateContainerinfraV1CertificatesResponse {
	return &CreateContainerinfraV1CertificatesResponse{
		CreateResult: createResult,
	}
}

// action function
func (oc *OpenstackClient) CreateContainerinfraV1Certificates(req *CreateContainerinfraV1CertificatesRequest) *CreateContainerinfraV1CertificatesResponse {
	return NewCreateContainerinfraV1CertificatesResponse(certificates.Create(oc.Client, req.Opts))

}

// request struct for the UpdateContainerinfraV1Certificates
type UpdateContainerinfraV1CertificatesRequest struct {
	ClusterID string
}

func NewUpdateContainerinfraV1CertificatesRequest() *UpdateContainerinfraV1CertificatesRequest {
	return &UpdateContainerinfraV1CertificatesRequest{}
}

// response struct for the UpdateContainerinfraV1Certificates
type UpdateContainerinfraV1CertificatesResponse struct {
	UpdateResult certificates.UpdateResult
}

func NewUpdateContainerinfraV1CertificatesResponse(updateResult certificates.UpdateResult) *UpdateContainerinfraV1CertificatesResponse {
	return &UpdateContainerinfraV1CertificatesResponse{
		UpdateResult: updateResult,
	}
}

// action function
func (oc *OpenstackClient) UpdateContainerinfraV1Certificates(req *UpdateContainerinfraV1CertificatesRequest) *UpdateContainerinfraV1CertificatesResponse {
	return NewUpdateContainerinfraV1CertificatesResponse(certificates.Update(oc.Client, req.ClusterID))

}
