package openstack

// Code generated by cloud manager.

import (
    "github.com/gophercloud/gophercloud/openstack/db/v1/users"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateDbV1Users
type CreateDbV1UsersRequest struct{
    InstanceID string
    Opts users.BatchCreateOpts
}

func NewCreateDbV1UsersRequest()*CreateDbV1UsersRequest{
    return &CreateDbV1UsersRequest{}
}

//response struct for the CreateDbV1Users
type CreateDbV1UsersResponse struct{
    CreateResult users.CreateResult
}

func NewCreateDbV1UsersResponse(createResult users.CreateResult,)*CreateDbV1UsersResponse {
    return &CreateDbV1UsersResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateDbV1Users(req *CreateDbV1UsersRequest)(*CreateDbV1UsersResponse){
    return NewCreateDbV1UsersResponse(users.Create(oc.Client,req.InstanceID,req.Opts, ))

}
//request struct for the ListDbV1Users
type ListDbV1UsersRequest struct{
    InstanceID string
}

func NewListDbV1UsersRequest()*ListDbV1UsersRequest{
    return &ListDbV1UsersRequest{}
}

//response struct for the ListDbV1Users
type ListDbV1UsersResponse struct{
    Pager pagination.Pager
}

func NewListDbV1UsersResponse(pager pagination.Pager,)*ListDbV1UsersResponse {
    return &ListDbV1UsersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListDbV1Users(req *ListDbV1UsersRequest)(*ListDbV1UsersResponse){
    return NewListDbV1UsersResponse(users.List(oc.Client,req.InstanceID, ))

}
//request struct for the DeleteDbV1Users
type DeleteDbV1UsersRequest struct{
    InstanceID string
    UserName string
}

func NewDeleteDbV1UsersRequest()*DeleteDbV1UsersRequest{
    return &DeleteDbV1UsersRequest{}
}

//response struct for the DeleteDbV1Users
type DeleteDbV1UsersResponse struct{
    DeleteResult users.DeleteResult
}

func NewDeleteDbV1UsersResponse(deleteResult users.DeleteResult,)*DeleteDbV1UsersResponse {
    return &DeleteDbV1UsersResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteDbV1Users(req *DeleteDbV1UsersRequest)(*DeleteDbV1UsersResponse){
    return NewDeleteDbV1UsersResponse(users.Delete(oc.Client,req.InstanceID,req.UserName, ))

}