package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/diagnostics"
)
//request struct for the GetDiagnostics
type GetDiagnosticsRequest struct{
    serverId string
}

func NewGetDiagnosticsRequest()*GetDiagnosticsRequest{
    return &GetDiagnosticsRequest{}
}

//response struct for the GetDiagnostics
type GetDiagnosticsResponse struct{
    ServerDiagnosticsResult diagnostics.serverDiagnosticsResult
}

func NewGetDiagnosticsResponse(serverDiagnosticsResult diagnostics.serverDiagnosticsResult,)*GetDiagnosticsResponse {
    return &GetDiagnosticsResponse{
            ServerDiagnosticsResult:serverDiagnosticsResult,
    }
}

// action function
func (oc *OpenstackClient) GetDiagnostics(request *GetDiagnosticsRequest)(*GetDiagnosticsResponse){
    return NewGetDiagnosticsResponse(diagnostics.Get(oc.client,request.serverId, ))

}