package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/flavors"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListDetailFlavors
type ListDetailFlavorsRequest struct{
    opts flavors.ListOptsBuilder
}

func NewListDetailFlavorsRequest()*ListDetailFlavorsRequest{
    return &ListDetailFlavorsRequest{}
}

//response struct for the ListDetailFlavors
type ListDetailFlavorsResponse struct{
    Pager pagination.Pager
}

func NewListDetailFlavorsResponse(pager pagination.Pager,)*ListDetailFlavorsResponse {
    return &ListDetailFlavorsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListDetailFlavors(request *ListDetailFlavorsRequest)(*ListDetailFlavorsResponse){
    return NewListDetailFlavorsResponse(flavors.ListDetail(oc.client,request.opts, ))

}
//request struct for the CreateFlavors
type CreateFlavorsRequest struct{
    opts flavors.CreateOptsBuilder
}

func NewCreateFlavorsRequest()*CreateFlavorsRequest{
    return &CreateFlavorsRequest{}
}

//response struct for the CreateFlavors
type CreateFlavorsResponse struct{
    CreateResult flavors.CreateResult
}

func NewCreateFlavorsResponse(createResult flavors.CreateResult,)*CreateFlavorsResponse {
    return &CreateFlavorsResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateFlavors(request *CreateFlavorsRequest)(*CreateFlavorsResponse){
    return NewCreateFlavorsResponse(flavors.Create(oc.client,request.opts, ))

}
//request struct for the UpdateFlavors
type UpdateFlavorsRequest struct{
    id string
    opts flavors.UpdateOptsBuilder
}

func NewUpdateFlavorsRequest()*UpdateFlavorsRequest{
    return &UpdateFlavorsRequest{}
}

//response struct for the UpdateFlavors
type UpdateFlavorsResponse struct{
    UpdateResult flavors.UpdateResult
}

func NewUpdateFlavorsResponse(updateResult flavors.UpdateResult,)*UpdateFlavorsResponse {
    return &UpdateFlavorsResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateFlavors(request *UpdateFlavorsRequest)(*UpdateFlavorsResponse){
    return NewUpdateFlavorsResponse(flavors.Update(oc.client,request.id,request.opts, ))

}
//request struct for the GetFlavors
type GetFlavorsRequest struct{
    id string
}

func NewGetFlavorsRequest()*GetFlavorsRequest{
    return &GetFlavorsRequest{}
}

//response struct for the GetFlavors
type GetFlavorsResponse struct{
    GetResult flavors.GetResult
}

func NewGetFlavorsResponse(getResult flavors.GetResult,)*GetFlavorsResponse {
    return &GetFlavorsResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetFlavors(request *GetFlavorsRequest)(*GetFlavorsResponse){
    return NewGetFlavorsResponse(flavors.Get(oc.client,request.id, ))

}
//request struct for the DeleteFlavors
type DeleteFlavorsRequest struct{
    id string
}

func NewDeleteFlavorsRequest()*DeleteFlavorsRequest{
    return &DeleteFlavorsRequest{}
}

//response struct for the DeleteFlavors
type DeleteFlavorsResponse struct{
    DeleteResult flavors.DeleteResult
}

func NewDeleteFlavorsResponse(deleteResult flavors.DeleteResult,)*DeleteFlavorsResponse {
    return &DeleteFlavorsResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteFlavors(request *DeleteFlavorsRequest)(*DeleteFlavorsResponse){
    return NewDeleteFlavorsResponse(flavors.Delete(oc.client,request.id, ))

}
//request struct for the ListAccessesFlavors
type ListAccessesFlavorsRequest struct{
    id string
}

func NewListAccessesFlavorsRequest()*ListAccessesFlavorsRequest{
    return &ListAccessesFlavorsRequest{}
}

//response struct for the ListAccessesFlavors
type ListAccessesFlavorsResponse struct{
    Pager pagination.Pager
}

func NewListAccessesFlavorsResponse(pager pagination.Pager,)*ListAccessesFlavorsResponse {
    return &ListAccessesFlavorsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListAccessesFlavors(request *ListAccessesFlavorsRequest)(*ListAccessesFlavorsResponse){
    return NewListAccessesFlavorsResponse(flavors.ListAccesses(oc.client,request.id, ))

}
//request struct for the AddAccessFlavors
type AddAccessFlavorsRequest struct{
    id string
    opts flavors.AddAccessOptsBuilder
}

func NewAddAccessFlavorsRequest()*AddAccessFlavorsRequest{
    return &AddAccessFlavorsRequest{}
}

//response struct for the AddAccessFlavors
type AddAccessFlavorsResponse struct{
    AddAccessResult flavors.AddAccessResult
}

func NewAddAccessFlavorsResponse(addAccessResult flavors.AddAccessResult,)*AddAccessFlavorsResponse {
    return &AddAccessFlavorsResponse{
            AddAccessResult:addAccessResult,
    }
}

// action function
func (oc *OpenstackClient) AddAccessFlavors(request *AddAccessFlavorsRequest)(*AddAccessFlavorsResponse){
    return NewAddAccessFlavorsResponse(flavors.AddAccess(oc.client,request.id,request.opts, ))

}
//request struct for the RemoveAccessFlavors
type RemoveAccessFlavorsRequest struct{
    id string
    opts flavors.RemoveAccessOptsBuilder
}

func NewRemoveAccessFlavorsRequest()*RemoveAccessFlavorsRequest{
    return &RemoveAccessFlavorsRequest{}
}

//response struct for the RemoveAccessFlavors
type RemoveAccessFlavorsResponse struct{
    RemoveAccessResult flavors.RemoveAccessResult
}

func NewRemoveAccessFlavorsResponse(removeAccessResult flavors.RemoveAccessResult,)*RemoveAccessFlavorsResponse {
    return &RemoveAccessFlavorsResponse{
            RemoveAccessResult:removeAccessResult,
    }
}

// action function
func (oc *OpenstackClient) RemoveAccessFlavors(request *RemoveAccessFlavorsRequest)(*RemoveAccessFlavorsResponse){
    return NewRemoveAccessFlavorsResponse(flavors.RemoveAccess(oc.client,request.id,request.opts, ))

}
//request struct for the ListExtraSpecsFlavors
type ListExtraSpecsFlavorsRequest struct{
    flavorID string
}

func NewListExtraSpecsFlavorsRequest()*ListExtraSpecsFlavorsRequest{
    return &ListExtraSpecsFlavorsRequest{}
}

//response struct for the ListExtraSpecsFlavors
type ListExtraSpecsFlavorsResponse struct{
    ListExtraSpecsResult flavors.ListExtraSpecsResult
}

func NewListExtraSpecsFlavorsResponse(listExtraSpecsResult flavors.ListExtraSpecsResult,)*ListExtraSpecsFlavorsResponse {
    return &ListExtraSpecsFlavorsResponse{
            ListExtraSpecsResult:listExtraSpecsResult,
    }
}

// action function
func (oc *OpenstackClient) ListExtraSpecsFlavors(request *ListExtraSpecsFlavorsRequest)(*ListExtraSpecsFlavorsResponse){
    return NewListExtraSpecsFlavorsResponse(flavors.ListExtraSpecs(oc.client,request.flavorID, ))

}
//request struct for the GetExtraSpecFlavors
type GetExtraSpecFlavorsRequest struct{
    flavorID string
    key string
}

func NewGetExtraSpecFlavorsRequest()*GetExtraSpecFlavorsRequest{
    return &GetExtraSpecFlavorsRequest{}
}

//response struct for the GetExtraSpecFlavors
type GetExtraSpecFlavorsResponse struct{
    GetExtraSpecResult flavors.GetExtraSpecResult
}

func NewGetExtraSpecFlavorsResponse(getExtraSpecResult flavors.GetExtraSpecResult,)*GetExtraSpecFlavorsResponse {
    return &GetExtraSpecFlavorsResponse{
            GetExtraSpecResult:getExtraSpecResult,
    }
}

// action function
func (oc *OpenstackClient) GetExtraSpecFlavors(request *GetExtraSpecFlavorsRequest)(*GetExtraSpecFlavorsResponse){
    return NewGetExtraSpecFlavorsResponse(flavors.GetExtraSpec(oc.client,request.flavorID,request.key, ))

}
//request struct for the CreateExtraSpecsFlavors
type CreateExtraSpecsFlavorsRequest struct{
    flavorID string
    opts flavors.CreateExtraSpecsOptsBuilder
}

func NewCreateExtraSpecsFlavorsRequest()*CreateExtraSpecsFlavorsRequest{
    return &CreateExtraSpecsFlavorsRequest{}
}

//response struct for the CreateExtraSpecsFlavors
type CreateExtraSpecsFlavorsResponse struct{
    CreateExtraSpecsResult flavors.CreateExtraSpecsResult
}

func NewCreateExtraSpecsFlavorsResponse(createExtraSpecsResult flavors.CreateExtraSpecsResult,)*CreateExtraSpecsFlavorsResponse {
    return &CreateExtraSpecsFlavorsResponse{
            CreateExtraSpecsResult:createExtraSpecsResult,
    }
}

// action function
func (oc *OpenstackClient) CreateExtraSpecsFlavors(request *CreateExtraSpecsFlavorsRequest)(*CreateExtraSpecsFlavorsResponse){
    return NewCreateExtraSpecsFlavorsResponse(flavors.CreateExtraSpecs(oc.client,request.flavorID,request.opts, ))

}
//request struct for the UpdateExtraSpecFlavors
type UpdateExtraSpecFlavorsRequest struct{
    flavorID string
    opts flavors.UpdateExtraSpecOptsBuilder
}

func NewUpdateExtraSpecFlavorsRequest()*UpdateExtraSpecFlavorsRequest{
    return &UpdateExtraSpecFlavorsRequest{}
}

//response struct for the UpdateExtraSpecFlavors
type UpdateExtraSpecFlavorsResponse struct{
    UpdateExtraSpecResult flavors.UpdateExtraSpecResult
}

func NewUpdateExtraSpecFlavorsResponse(updateExtraSpecResult flavors.UpdateExtraSpecResult,)*UpdateExtraSpecFlavorsResponse {
    return &UpdateExtraSpecFlavorsResponse{
            UpdateExtraSpecResult:updateExtraSpecResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateExtraSpecFlavors(request *UpdateExtraSpecFlavorsRequest)(*UpdateExtraSpecFlavorsResponse){
    return NewUpdateExtraSpecFlavorsResponse(flavors.UpdateExtraSpec(oc.client,request.flavorID,request.opts, ))

}
//request struct for the DeleteExtraSpecFlavors
type DeleteExtraSpecFlavorsRequest struct{
    flavorID string
    key string
}

func NewDeleteExtraSpecFlavorsRequest()*DeleteExtraSpecFlavorsRequest{
    return &DeleteExtraSpecFlavorsRequest{}
}

//response struct for the DeleteExtraSpecFlavors
type DeleteExtraSpecFlavorsResponse struct{
    DeleteExtraSpecResult flavors.DeleteExtraSpecResult
}

func NewDeleteExtraSpecFlavorsResponse(deleteExtraSpecResult flavors.DeleteExtraSpecResult,)*DeleteExtraSpecFlavorsResponse {
    return &DeleteExtraSpecFlavorsResponse{
            DeleteExtraSpecResult:deleteExtraSpecResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteExtraSpecFlavors(request *DeleteExtraSpecFlavorsRequest)(*DeleteExtraSpecFlavorsResponse){
    return NewDeleteExtraSpecFlavorsResponse(flavors.DeleteExtraSpec(oc.client,request.flavorID,request.key, ))

}