package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/identity/v2/users"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateIdentityV2Users
type CreateIdentityV2UsersRequest struct{
    Opts users.CreateOpts
}

func NewCreateIdentityV2UsersRequest()*CreateIdentityV2UsersRequest{
    return &CreateIdentityV2UsersRequest{}
}

//response struct for the CreateIdentityV2Users
type CreateIdentityV2UsersResponse struct{
    CreateResult users.CreateResult
}

func NewCreateIdentityV2UsersResponse(createResult users.CreateResult,)*CreateIdentityV2UsersResponse {
    return &CreateIdentityV2UsersResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateIdentityV2Users(req *CreateIdentityV2UsersRequest)(*CreateIdentityV2UsersResponse){
    return NewCreateIdentityV2UsersResponse(users.Create(oc.Client,req.Opts, ))

}
//request struct for the GetIdentityV2Users
type GetIdentityV2UsersRequest struct{
    Id string
}

func NewGetIdentityV2UsersRequest()*GetIdentityV2UsersRequest{
    return &GetIdentityV2UsersRequest{}
}

//response struct for the GetIdentityV2Users
type GetIdentityV2UsersResponse struct{
    GetResult users.GetResult
}

func NewGetIdentityV2UsersResponse(getResult users.GetResult,)*GetIdentityV2UsersResponse {
    return &GetIdentityV2UsersResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetIdentityV2Users(req *GetIdentityV2UsersRequest)(*GetIdentityV2UsersResponse){
    return NewGetIdentityV2UsersResponse(users.Get(oc.Client,req.Id, ))

}
//request struct for the UpdateIdentityV2Users
type UpdateIdentityV2UsersRequest struct{
    Id string
    Opts users.UpdateOpts
}

func NewUpdateIdentityV2UsersRequest()*UpdateIdentityV2UsersRequest{
    return &UpdateIdentityV2UsersRequest{}
}

//response struct for the UpdateIdentityV2Users
type UpdateIdentityV2UsersResponse struct{
    UpdateResult users.UpdateResult
}

func NewUpdateIdentityV2UsersResponse(updateResult users.UpdateResult,)*UpdateIdentityV2UsersResponse {
    return &UpdateIdentityV2UsersResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateIdentityV2Users(req *UpdateIdentityV2UsersRequest)(*UpdateIdentityV2UsersResponse){
    return NewUpdateIdentityV2UsersResponse(users.Update(oc.Client,req.Id,req.Opts, ))

}
//request struct for the DeleteIdentityV2Users
type DeleteIdentityV2UsersRequest struct{
    Id string
}

func NewDeleteIdentityV2UsersRequest()*DeleteIdentityV2UsersRequest{
    return &DeleteIdentityV2UsersRequest{}
}

//response struct for the DeleteIdentityV2Users
type DeleteIdentityV2UsersResponse struct{
    DeleteResult users.DeleteResult
}

func NewDeleteIdentityV2UsersResponse(deleteResult users.DeleteResult,)*DeleteIdentityV2UsersResponse {
    return &DeleteIdentityV2UsersResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteIdentityV2Users(req *DeleteIdentityV2UsersRequest)(*DeleteIdentityV2UsersResponse){
    return NewDeleteIdentityV2UsersResponse(users.Delete(oc.Client,req.Id, ))

}
//request struct for the ListRolesIdentityV2Users
type ListRolesIdentityV2UsersRequest struct{
    TenantID string
    UserID string
}

func NewListRolesIdentityV2UsersRequest()*ListRolesIdentityV2UsersRequest{
    return &ListRolesIdentityV2UsersRequest{}
}

//response struct for the ListRolesIdentityV2Users
type ListRolesIdentityV2UsersResponse struct{
    Pager pagination.Pager
}

func NewListRolesIdentityV2UsersResponse(pager pagination.Pager,)*ListRolesIdentityV2UsersResponse {
    return &ListRolesIdentityV2UsersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListRolesIdentityV2Users(req *ListRolesIdentityV2UsersRequest)(*ListRolesIdentityV2UsersResponse){
    return NewListRolesIdentityV2UsersResponse(users.ListRoles(oc.Client,req.TenantID,req.UserID, ))

}