package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/identity/v3/catalog"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListIdentityV3Catalog
type ListIdentityV3CatalogRequest struct{
}

func NewListIdentityV3CatalogRequest()*ListIdentityV3CatalogRequest{
    return &ListIdentityV3CatalogRequest{}
}

//response struct for the ListIdentityV3Catalog
type ListIdentityV3CatalogResponse struct{
    Pager pagination.Pager
}

func NewListIdentityV3CatalogResponse(pager pagination.Pager,)*ListIdentityV3CatalogResponse {
    return &ListIdentityV3CatalogResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListIdentityV3Catalog(req *ListIdentityV3CatalogRequest)(*ListIdentityV3CatalogResponse){
    return NewListIdentityV3CatalogResponse(catalog.List(oc.Client, ))

}