package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport"
)
//request struct for the CreateImageserviceV2Imageimport
type CreateImageserviceV2ImageimportRequest struct{
    ImageID string
    Opts imageimport.CreateOpts
}

func NewCreateImageserviceV2ImageimportRequest()*CreateImageserviceV2ImageimportRequest{
    return &CreateImageserviceV2ImageimportRequest{}
}

//response struct for the CreateImageserviceV2Imageimport
type CreateImageserviceV2ImageimportResponse struct{
    CreateResult imageimport.CreateResult
}

func NewCreateImageserviceV2ImageimportResponse(createResult imageimport.CreateResult,)*CreateImageserviceV2ImageimportResponse {
    return &CreateImageserviceV2ImageimportResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateImageserviceV2Imageimport(req *CreateImageserviceV2ImageimportRequest)(*CreateImageserviceV2ImageimportResponse){
    return NewCreateImageserviceV2ImageimportResponse(imageimport.Create(oc.Client,req.ImageID,req.Opts, ))

}