package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListLoadbalancerV2Apiversions
type ListLoadbalancerV2ApiversionsRequest struct{
}

func NewListLoadbalancerV2ApiversionsRequest()*ListLoadbalancerV2ApiversionsRequest{
    return &ListLoadbalancerV2ApiversionsRequest{}
}

//response struct for the ListLoadbalancerV2Apiversions
type ListLoadbalancerV2ApiversionsResponse struct{
    Pager pagination.Pager
}

func NewListLoadbalancerV2ApiversionsResponse(pager pagination.Pager,)*ListLoadbalancerV2ApiversionsResponse {
    return &ListLoadbalancerV2ApiversionsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListLoadbalancerV2Apiversions(request *ListLoadbalancerV2ApiversionsRequest)(*ListLoadbalancerV2ApiversionsResponse){
    return NewListLoadbalancerV2ApiversionsResponse(apiversions.List(oc.client, ))

}