package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListNetworkingV2ExtensionsLbaas_v2Monitors
type ListNetworkingV2ExtensionsLbaas_v2MonitorsRequest struct{
    Opts monitors.ListOptsBuilder
}

func NewListNetworkingV2ExtensionsLbaas_v2MonitorsRequest()*ListNetworkingV2ExtensionsLbaas_v2MonitorsRequest{
    return &ListNetworkingV2ExtensionsLbaas_v2MonitorsRequest{}
}

//response struct for the ListNetworkingV2ExtensionsLbaas_v2Monitors
type ListNetworkingV2ExtensionsLbaas_v2MonitorsResponse struct{
    Pager pagination.Pager
}

func NewListNetworkingV2ExtensionsLbaas_v2MonitorsResponse(pager pagination.Pager,)*ListNetworkingV2ExtensionsLbaas_v2MonitorsResponse {
    return &ListNetworkingV2ExtensionsLbaas_v2MonitorsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListNetworkingV2ExtensionsLbaas_v2Monitors(req *ListNetworkingV2ExtensionsLbaas_v2MonitorsRequest)(*ListNetworkingV2ExtensionsLbaas_v2MonitorsResponse){
    return NewListNetworkingV2ExtensionsLbaas_v2MonitorsResponse(monitors.List(oc.client,req.Opts, ))

}
//request struct for the CreateNetworkingV2ExtensionsLbaas_v2Monitors
type CreateNetworkingV2ExtensionsLbaas_v2MonitorsRequest struct{
    Opts monitors.CreateOptsBuilder
}

func NewCreateNetworkingV2ExtensionsLbaas_v2MonitorsRequest()*CreateNetworkingV2ExtensionsLbaas_v2MonitorsRequest{
    return &CreateNetworkingV2ExtensionsLbaas_v2MonitorsRequest{}
}

//response struct for the CreateNetworkingV2ExtensionsLbaas_v2Monitors
type CreateNetworkingV2ExtensionsLbaas_v2MonitorsResponse struct{
    CreateResult monitors.CreateResult
}

func NewCreateNetworkingV2ExtensionsLbaas_v2MonitorsResponse(createResult monitors.CreateResult,)*CreateNetworkingV2ExtensionsLbaas_v2MonitorsResponse {
    return &CreateNetworkingV2ExtensionsLbaas_v2MonitorsResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateNetworkingV2ExtensionsLbaas_v2Monitors(req *CreateNetworkingV2ExtensionsLbaas_v2MonitorsRequest)(*CreateNetworkingV2ExtensionsLbaas_v2MonitorsResponse){
    return NewCreateNetworkingV2ExtensionsLbaas_v2MonitorsResponse(monitors.Create(oc.client,req.Opts, ))

}
//request struct for the GetNetworkingV2ExtensionsLbaas_v2Monitors
type GetNetworkingV2ExtensionsLbaas_v2MonitorsRequest struct{
    Id string
}

func NewGetNetworkingV2ExtensionsLbaas_v2MonitorsRequest()*GetNetworkingV2ExtensionsLbaas_v2MonitorsRequest{
    return &GetNetworkingV2ExtensionsLbaas_v2MonitorsRequest{}
}

//response struct for the GetNetworkingV2ExtensionsLbaas_v2Monitors
type GetNetworkingV2ExtensionsLbaas_v2MonitorsResponse struct{
    GetResult monitors.GetResult
}

func NewGetNetworkingV2ExtensionsLbaas_v2MonitorsResponse(getResult monitors.GetResult,)*GetNetworkingV2ExtensionsLbaas_v2MonitorsResponse {
    return &GetNetworkingV2ExtensionsLbaas_v2MonitorsResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetNetworkingV2ExtensionsLbaas_v2Monitors(req *GetNetworkingV2ExtensionsLbaas_v2MonitorsRequest)(*GetNetworkingV2ExtensionsLbaas_v2MonitorsResponse){
    return NewGetNetworkingV2ExtensionsLbaas_v2MonitorsResponse(monitors.Get(oc.client,req.Id, ))

}
//request struct for the UpdateNetworkingV2ExtensionsLbaas_v2Monitors
type UpdateNetworkingV2ExtensionsLbaas_v2MonitorsRequest struct{
    Id string
    Opts monitors.UpdateOptsBuilder
}

func NewUpdateNetworkingV2ExtensionsLbaas_v2MonitorsRequest()*UpdateNetworkingV2ExtensionsLbaas_v2MonitorsRequest{
    return &UpdateNetworkingV2ExtensionsLbaas_v2MonitorsRequest{}
}

//response struct for the UpdateNetworkingV2ExtensionsLbaas_v2Monitors
type UpdateNetworkingV2ExtensionsLbaas_v2MonitorsResponse struct{
    UpdateResult monitors.UpdateResult
}

func NewUpdateNetworkingV2ExtensionsLbaas_v2MonitorsResponse(updateResult monitors.UpdateResult,)*UpdateNetworkingV2ExtensionsLbaas_v2MonitorsResponse {
    return &UpdateNetworkingV2ExtensionsLbaas_v2MonitorsResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateNetworkingV2ExtensionsLbaas_v2Monitors(req *UpdateNetworkingV2ExtensionsLbaas_v2MonitorsRequest)(*UpdateNetworkingV2ExtensionsLbaas_v2MonitorsResponse){
    return NewUpdateNetworkingV2ExtensionsLbaas_v2MonitorsResponse(monitors.Update(oc.client,req.Id,req.Opts, ))

}
//request struct for the DeleteNetworkingV2ExtensionsLbaas_v2Monitors
type DeleteNetworkingV2ExtensionsLbaas_v2MonitorsRequest struct{
    Id string
}

func NewDeleteNetworkingV2ExtensionsLbaas_v2MonitorsRequest()*DeleteNetworkingV2ExtensionsLbaas_v2MonitorsRequest{
    return &DeleteNetworkingV2ExtensionsLbaas_v2MonitorsRequest{}
}

//response struct for the DeleteNetworkingV2ExtensionsLbaas_v2Monitors
type DeleteNetworkingV2ExtensionsLbaas_v2MonitorsResponse struct{
    DeleteResult monitors.DeleteResult
}

func NewDeleteNetworkingV2ExtensionsLbaas_v2MonitorsResponse(deleteResult monitors.DeleteResult,)*DeleteNetworkingV2ExtensionsLbaas_v2MonitorsResponse {
    return &DeleteNetworkingV2ExtensionsLbaas_v2MonitorsResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteNetworkingV2ExtensionsLbaas_v2Monitors(req *DeleteNetworkingV2ExtensionsLbaas_v2MonitorsRequest)(*DeleteNetworkingV2ExtensionsLbaas_v2MonitorsResponse){
    return NewDeleteNetworkingV2ExtensionsLbaas_v2MonitorsResponse(monitors.Delete(oc.client,req.Id, ))

}