package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/networks"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListNetworks
type ListNetworksRequest struct{
}

func NewListNetworksRequest()*ListNetworksRequest{
    return &ListNetworksRequest{}
}

//response struct for the ListNetworks
type ListNetworksResponse struct{
    Pager pagination.Pager
}

func NewListNetworksResponse(pager pagination.Pager,)*ListNetworksResponse {
    return &ListNetworksResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListNetworks(request *ListNetworksRequest)(*ListNetworksResponse){
    return NewListNetworksResponse(networks.List(oc.client, ))

}
//request struct for the GetNetworks
type GetNetworksRequest struct{
    id string
}

func NewGetNetworksRequest()*GetNetworksRequest{
    return &GetNetworksRequest{}
}

//response struct for the GetNetworks
type GetNetworksResponse struct{
    GetResult networks.GetResult
}

func NewGetNetworksResponse(getResult networks.GetResult,)*GetNetworksResponse {
    return &GetNetworksResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetNetworks(request *GetNetworksRequest)(*GetNetworksResponse){
    return NewGetNetworksResponse(networks.Get(oc.client,request.id, ))

}