package openstack

// Code generated by cloud manager.

import (
    "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListNetworkingV2ExtensionsLayer3Routers
type ListNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Opts routers.ListOpts
}

func NewListNetworkingV2ExtensionsLayer3RoutersRequest()*ListNetworkingV2ExtensionsLayer3RoutersRequest{
    return &ListNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the ListNetworkingV2ExtensionsLayer3Routers
type ListNetworkingV2ExtensionsLayer3RoutersResponse struct{
    Pager pagination.Pager
}

func NewListNetworkingV2ExtensionsLayer3RoutersResponse(pager pagination.Pager,)*ListNetworkingV2ExtensionsLayer3RoutersResponse {
    return &ListNetworkingV2ExtensionsLayer3RoutersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListNetworkingV2ExtensionsLayer3Routers(req *ListNetworkingV2ExtensionsLayer3RoutersRequest)(*ListNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewListNetworkingV2ExtensionsLayer3RoutersResponse(routers.List(oc.Client,req.Opts, ))

}
//request struct for the CreateNetworkingV2ExtensionsLayer3Routers
type CreateNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Opts routers.CreateOpts
}

func NewCreateNetworkingV2ExtensionsLayer3RoutersRequest()*CreateNetworkingV2ExtensionsLayer3RoutersRequest{
    return &CreateNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the CreateNetworkingV2ExtensionsLayer3Routers
type CreateNetworkingV2ExtensionsLayer3RoutersResponse struct{
    CreateResult routers.CreateResult
}

func NewCreateNetworkingV2ExtensionsLayer3RoutersResponse(createResult routers.CreateResult,)*CreateNetworkingV2ExtensionsLayer3RoutersResponse {
    return &CreateNetworkingV2ExtensionsLayer3RoutersResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateNetworkingV2ExtensionsLayer3Routers(req *CreateNetworkingV2ExtensionsLayer3RoutersRequest)(*CreateNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewCreateNetworkingV2ExtensionsLayer3RoutersResponse(routers.Create(oc.Client,req.Opts, ))

}
//request struct for the GetNetworkingV2ExtensionsLayer3Routers
type GetNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Id string
}

func NewGetNetworkingV2ExtensionsLayer3RoutersRequest()*GetNetworkingV2ExtensionsLayer3RoutersRequest{
    return &GetNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the GetNetworkingV2ExtensionsLayer3Routers
type GetNetworkingV2ExtensionsLayer3RoutersResponse struct{
    GetResult routers.GetResult
}

func NewGetNetworkingV2ExtensionsLayer3RoutersResponse(getResult routers.GetResult,)*GetNetworkingV2ExtensionsLayer3RoutersResponse {
    return &GetNetworkingV2ExtensionsLayer3RoutersResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetNetworkingV2ExtensionsLayer3Routers(req *GetNetworkingV2ExtensionsLayer3RoutersRequest)(*GetNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewGetNetworkingV2ExtensionsLayer3RoutersResponse(routers.Get(oc.Client,req.Id, ))

}
//request struct for the UpdateNetworkingV2ExtensionsLayer3Routers
type UpdateNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Id string
    Opts routers.UpdateOpts
}

func NewUpdateNetworkingV2ExtensionsLayer3RoutersRequest()*UpdateNetworkingV2ExtensionsLayer3RoutersRequest{
    return &UpdateNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the UpdateNetworkingV2ExtensionsLayer3Routers
type UpdateNetworkingV2ExtensionsLayer3RoutersResponse struct{
    UpdateResult routers.UpdateResult
}

func NewUpdateNetworkingV2ExtensionsLayer3RoutersResponse(updateResult routers.UpdateResult,)*UpdateNetworkingV2ExtensionsLayer3RoutersResponse {
    return &UpdateNetworkingV2ExtensionsLayer3RoutersResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateNetworkingV2ExtensionsLayer3Routers(req *UpdateNetworkingV2ExtensionsLayer3RoutersRequest)(*UpdateNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewUpdateNetworkingV2ExtensionsLayer3RoutersResponse(routers.Update(oc.Client,req.Id,req.Opts, ))

}
//request struct for the DeleteNetworkingV2ExtensionsLayer3Routers
type DeleteNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Id string
}

func NewDeleteNetworkingV2ExtensionsLayer3RoutersRequest()*DeleteNetworkingV2ExtensionsLayer3RoutersRequest{
    return &DeleteNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the DeleteNetworkingV2ExtensionsLayer3Routers
type DeleteNetworkingV2ExtensionsLayer3RoutersResponse struct{
    DeleteResult routers.DeleteResult
}

func NewDeleteNetworkingV2ExtensionsLayer3RoutersResponse(deleteResult routers.DeleteResult,)*DeleteNetworkingV2ExtensionsLayer3RoutersResponse {
    return &DeleteNetworkingV2ExtensionsLayer3RoutersResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteNetworkingV2ExtensionsLayer3Routers(req *DeleteNetworkingV2ExtensionsLayer3RoutersRequest)(*DeleteNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewDeleteNetworkingV2ExtensionsLayer3RoutersResponse(routers.Delete(oc.Client,req.Id, ))

}
//request struct for the AddInterfaceNetworkingV2ExtensionsLayer3Routers
type AddInterfaceNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Id string
    Opts routers.AddInterfaceOpts
}

func NewAddInterfaceNetworkingV2ExtensionsLayer3RoutersRequest()*AddInterfaceNetworkingV2ExtensionsLayer3RoutersRequest{
    return &AddInterfaceNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the AddInterfaceNetworkingV2ExtensionsLayer3Routers
type AddInterfaceNetworkingV2ExtensionsLayer3RoutersResponse struct{
    InterfaceResult routers.InterfaceResult
}

func NewAddInterfaceNetworkingV2ExtensionsLayer3RoutersResponse(interfaceResult routers.InterfaceResult,)*AddInterfaceNetworkingV2ExtensionsLayer3RoutersResponse {
    return &AddInterfaceNetworkingV2ExtensionsLayer3RoutersResponse{
            InterfaceResult:interfaceResult,
    }
}

// action function
func (oc *OpenstackClient) AddInterfaceNetworkingV2ExtensionsLayer3Routers(req *AddInterfaceNetworkingV2ExtensionsLayer3RoutersRequest)(*AddInterfaceNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewAddInterfaceNetworkingV2ExtensionsLayer3RoutersResponse(routers.AddInterface(oc.Client,req.Id,req.Opts, ))

}
//request struct for the RemoveInterfaceNetworkingV2ExtensionsLayer3Routers
type RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Id string
    Opts routers.RemoveInterfaceOpts
}

func NewRemoveInterfaceNetworkingV2ExtensionsLayer3RoutersRequest()*RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersRequest{
    return &RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the RemoveInterfaceNetworkingV2ExtensionsLayer3Routers
type RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersResponse struct{
    InterfaceResult routers.InterfaceResult
}

func NewRemoveInterfaceNetworkingV2ExtensionsLayer3RoutersResponse(interfaceResult routers.InterfaceResult,)*RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersResponse {
    return &RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersResponse{
            InterfaceResult:interfaceResult,
    }
}

// action function
func (oc *OpenstackClient) RemoveInterfaceNetworkingV2ExtensionsLayer3Routers(req *RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersRequest)(*RemoveInterfaceNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewRemoveInterfaceNetworkingV2ExtensionsLayer3RoutersResponse(routers.RemoveInterface(oc.Client,req.Id,req.Opts, ))

}
//request struct for the ListL3AgentsNetworkingV2ExtensionsLayer3Routers
type ListL3AgentsNetworkingV2ExtensionsLayer3RoutersRequest struct{
    Id string
}

func NewListL3AgentsNetworkingV2ExtensionsLayer3RoutersRequest()*ListL3AgentsNetworkingV2ExtensionsLayer3RoutersRequest{
    return &ListL3AgentsNetworkingV2ExtensionsLayer3RoutersRequest{}
}

//response struct for the ListL3AgentsNetworkingV2ExtensionsLayer3Routers
type ListL3AgentsNetworkingV2ExtensionsLayer3RoutersResponse struct{
    Pager pagination.Pager
}

func NewListL3AgentsNetworkingV2ExtensionsLayer3RoutersResponse(pager pagination.Pager,)*ListL3AgentsNetworkingV2ExtensionsLayer3RoutersResponse {
    return &ListL3AgentsNetworkingV2ExtensionsLayer3RoutersResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListL3AgentsNetworkingV2ExtensionsLayer3Routers(req *ListL3AgentsNetworkingV2ExtensionsLayer3RoutersRequest)(*ListL3AgentsNetworkingV2ExtensionsLayer3RoutersResponse){
    return NewListL3AgentsNetworkingV2ExtensionsLayer3RoutersResponse(routers.ListL3Agents(oc.Client,req.Id, ))

}