package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/objectstorage/v1/accounts"
)
//request struct for the GetObjectstorageV1Accounts
type GetObjectstorageV1AccountsRequest struct{
    Opts accounts.GetOpts
}

func NewGetObjectstorageV1AccountsRequest()*GetObjectstorageV1AccountsRequest{
    return &GetObjectstorageV1AccountsRequest{}
}

//response struct for the GetObjectstorageV1Accounts
type GetObjectstorageV1AccountsResponse struct{
    GetResult accounts.GetResult
}

func NewGetObjectstorageV1AccountsResponse(getResult accounts.GetResult,)*GetObjectstorageV1AccountsResponse {
    return &GetObjectstorageV1AccountsResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetObjectstorageV1Accounts(req *GetObjectstorageV1AccountsRequest)(*GetObjectstorageV1AccountsResponse){
    return NewGetObjectstorageV1AccountsResponse(accounts.Get(oc.Client,req.Opts, ))

}
//request struct for the UpdateObjectstorageV1Accounts
type UpdateObjectstorageV1AccountsRequest struct{
    Opts accounts.UpdateOpts
}

func NewUpdateObjectstorageV1AccountsRequest()*UpdateObjectstorageV1AccountsRequest{
    return &UpdateObjectstorageV1AccountsRequest{}
}

//response struct for the UpdateObjectstorageV1Accounts
type UpdateObjectstorageV1AccountsResponse struct{
    UpdateResult accounts.UpdateResult
}

func NewUpdateObjectstorageV1AccountsResponse(updateResult accounts.UpdateResult,)*UpdateObjectstorageV1AccountsResponse {
    return &UpdateObjectstorageV1AccountsResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateObjectstorageV1Accounts(req *UpdateObjectstorageV1AccountsRequest)(*UpdateObjectstorageV1AccountsResponse){
    return NewUpdateObjectstorageV1AccountsResponse(accounts.Update(oc.Client,req.Opts, ))

}