package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/orchestration/v1/apiversions"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListVersionsOrchestrationV1Apiversions
type ListVersionsOrchestrationV1ApiversionsRequest struct{
}

func NewListVersionsOrchestrationV1ApiversionsRequest()*ListVersionsOrchestrationV1ApiversionsRequest{
    return &ListVersionsOrchestrationV1ApiversionsRequest{}
}

//response struct for the ListVersionsOrchestrationV1Apiversions
type ListVersionsOrchestrationV1ApiversionsResponse struct{
    Pager pagination.Pager
}

func NewListVersionsOrchestrationV1ApiversionsResponse(pager pagination.Pager,)*ListVersionsOrchestrationV1ApiversionsResponse {
    return &ListVersionsOrchestrationV1ApiversionsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListVersionsOrchestrationV1Apiversions(req *ListVersionsOrchestrationV1ApiversionsRequest)(*ListVersionsOrchestrationV1ApiversionsResponse){
    return NewListVersionsOrchestrationV1ApiversionsResponse(apiversions.ListVersions(oc.client, ))

}