package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/remoteconsoles"
)
//request struct for the CreateRemoteconsoles
type CreateRemoteconsolesRequest struct{
    serverID string
    opts remoteconsoles.CreateOptsBuilder
}

func NewCreateRemoteconsolesRequest()*CreateRemoteconsolesRequest{
    return &CreateRemoteconsolesRequest{}
}

//response struct for the CreateRemoteconsoles
type CreateRemoteconsolesResponse struct{
    CreateResult remoteconsoles.CreateResult
}

func NewCreateRemoteconsolesResponse(createResult remoteconsoles.CreateResult,)*CreateRemoteconsolesResponse {
    return &CreateRemoteconsolesResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateRemoteconsoles(request *CreateRemoteconsolesRequest)(*CreateRemoteconsolesResponse){
    return NewCreateRemoteconsolesResponse(remoteconsoles.Create(oc.client,request.serverID,request.opts, ))

}