package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/secgroups"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the commonListSecgroups
type commonListSecgroupsRequest struct{
    url string
}

func NewcommonListSecgroupsRequest()*commonListSecgroupsRequest{
    return &commonListSecgroupsRequest{}
}

//response struct for the commonListSecgroups
type commonListSecgroupsResponse struct{
    Pager pagination.Pager
}

func NewcommonListSecgroupsResponse(pager pagination.Pager,)*commonListSecgroupsResponse {
    return &commonListSecgroupsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) commonListSecgroups(request *commonListSecgroupsRequest)(*commonListSecgroupsResponse){
    return NewcommonListSecgroupsResponse(secgroups.commonList(oc.client,request.url, ))

}
//request struct for the ListSecgroups
type ListSecgroupsRequest struct{
}

func NewListSecgroupsRequest()*ListSecgroupsRequest{
    return &ListSecgroupsRequest{}
}

//response struct for the ListSecgroups
type ListSecgroupsResponse struct{
    Pager pagination.Pager
}

func NewListSecgroupsResponse(pager pagination.Pager,)*ListSecgroupsResponse {
    return &ListSecgroupsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListSecgroups(request *ListSecgroupsRequest)(*ListSecgroupsResponse){
    return NewListSecgroupsResponse(secgroups.List(oc.client, ))

}
//request struct for the ListByServerSecgroups
type ListByServerSecgroupsRequest struct{
    serverID string
}

func NewListByServerSecgroupsRequest()*ListByServerSecgroupsRequest{
    return &ListByServerSecgroupsRequest{}
}

//response struct for the ListByServerSecgroups
type ListByServerSecgroupsResponse struct{
    Pager pagination.Pager
}

func NewListByServerSecgroupsResponse(pager pagination.Pager,)*ListByServerSecgroupsResponse {
    return &ListByServerSecgroupsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListByServerSecgroups(request *ListByServerSecgroupsRequest)(*ListByServerSecgroupsResponse){
    return NewListByServerSecgroupsResponse(secgroups.ListByServer(oc.client,request.serverID, ))

}
//request struct for the CreateSecgroups
type CreateSecgroupsRequest struct{
    opts secgroups.CreateOptsBuilder
}

func NewCreateSecgroupsRequest()*CreateSecgroupsRequest{
    return &CreateSecgroupsRequest{}
}

//response struct for the CreateSecgroups
type CreateSecgroupsResponse struct{
    CreateResult secgroups.CreateResult
}

func NewCreateSecgroupsResponse(createResult secgroups.CreateResult,)*CreateSecgroupsResponse {
    return &CreateSecgroupsResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateSecgroups(request *CreateSecgroupsRequest)(*CreateSecgroupsResponse){
    return NewCreateSecgroupsResponse(secgroups.Create(oc.client,request.opts, ))

}
//request struct for the UpdateSecgroups
type UpdateSecgroupsRequest struct{
    id string
    opts secgroups.UpdateOptsBuilder
}

func NewUpdateSecgroupsRequest()*UpdateSecgroupsRequest{
    return &UpdateSecgroupsRequest{}
}

//response struct for the UpdateSecgroups
type UpdateSecgroupsResponse struct{
    UpdateResult secgroups.UpdateResult
}

func NewUpdateSecgroupsResponse(updateResult secgroups.UpdateResult,)*UpdateSecgroupsResponse {
    return &UpdateSecgroupsResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateSecgroups(request *UpdateSecgroupsRequest)(*UpdateSecgroupsResponse){
    return NewUpdateSecgroupsResponse(secgroups.Update(oc.client,request.id,request.opts, ))

}
//request struct for the GetSecgroups
type GetSecgroupsRequest struct{
    id string
}

func NewGetSecgroupsRequest()*GetSecgroupsRequest{
    return &GetSecgroupsRequest{}
}

//response struct for the GetSecgroups
type GetSecgroupsResponse struct{
    GetResult secgroups.GetResult
}

func NewGetSecgroupsResponse(getResult secgroups.GetResult,)*GetSecgroupsResponse {
    return &GetSecgroupsResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetSecgroups(request *GetSecgroupsRequest)(*GetSecgroupsResponse){
    return NewGetSecgroupsResponse(secgroups.Get(oc.client,request.id, ))

}
//request struct for the DeleteSecgroups
type DeleteSecgroupsRequest struct{
    id string
}

func NewDeleteSecgroupsRequest()*DeleteSecgroupsRequest{
    return &DeleteSecgroupsRequest{}
}

//response struct for the DeleteSecgroups
type DeleteSecgroupsResponse struct{
    DeleteResult secgroups.DeleteResult
}

func NewDeleteSecgroupsResponse(deleteResult secgroups.DeleteResult,)*DeleteSecgroupsResponse {
    return &DeleteSecgroupsResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteSecgroups(request *DeleteSecgroupsRequest)(*DeleteSecgroupsResponse){
    return NewDeleteSecgroupsResponse(secgroups.Delete(oc.client,request.id, ))

}
//request struct for the CreateRuleSecgroups
type CreateRuleSecgroupsRequest struct{
    opts secgroups.CreateRuleOptsBuilder
}

func NewCreateRuleSecgroupsRequest()*CreateRuleSecgroupsRequest{
    return &CreateRuleSecgroupsRequest{}
}

//response struct for the CreateRuleSecgroups
type CreateRuleSecgroupsResponse struct{
    CreateRuleResult secgroups.CreateRuleResult
}

func NewCreateRuleSecgroupsResponse(createRuleResult secgroups.CreateRuleResult,)*CreateRuleSecgroupsResponse {
    return &CreateRuleSecgroupsResponse{
            CreateRuleResult:createRuleResult,
    }
}

// action function
func (oc *OpenstackClient) CreateRuleSecgroups(request *CreateRuleSecgroupsRequest)(*CreateRuleSecgroupsResponse){
    return NewCreateRuleSecgroupsResponse(secgroups.CreateRule(oc.client,request.opts, ))

}
//request struct for the DeleteRuleSecgroups
type DeleteRuleSecgroupsRequest struct{
    id string
}

func NewDeleteRuleSecgroupsRequest()*DeleteRuleSecgroupsRequest{
    return &DeleteRuleSecgroupsRequest{}
}

//response struct for the DeleteRuleSecgroups
type DeleteRuleSecgroupsResponse struct{
    DeleteRuleResult secgroups.DeleteRuleResult
}

func NewDeleteRuleSecgroupsResponse(deleteRuleResult secgroups.DeleteRuleResult,)*DeleteRuleSecgroupsResponse {
    return &DeleteRuleSecgroupsResponse{
            DeleteRuleResult:deleteRuleResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteRuleSecgroups(request *DeleteRuleSecgroupsRequest)(*DeleteRuleSecgroupsResponse){
    return NewDeleteRuleSecgroupsResponse(secgroups.DeleteRule(oc.client,request.id, ))

}
//request struct for the AddServerSecgroups
type AddServerSecgroupsRequest struct{
    serverID string
    groupName string
}

func NewAddServerSecgroupsRequest()*AddServerSecgroupsRequest{
    return &AddServerSecgroupsRequest{}
}

//response struct for the AddServerSecgroups
type AddServerSecgroupsResponse struct{
    AddServerResult secgroups.AddServerResult
}

func NewAddServerSecgroupsResponse(addServerResult secgroups.AddServerResult,)*AddServerSecgroupsResponse {
    return &AddServerSecgroupsResponse{
            AddServerResult:addServerResult,
    }
}

// action function
func (oc *OpenstackClient) AddServerSecgroups(request *AddServerSecgroupsRequest)(*AddServerSecgroupsResponse){
    return NewAddServerSecgroupsResponse(secgroups.AddServer(oc.client,request.serverID,request.groupName, ))

}
//request struct for the RemoveServerSecgroups
type RemoveServerSecgroupsRequest struct{
    serverID string
    groupName string
}

func NewRemoveServerSecgroupsRequest()*RemoveServerSecgroupsRequest{
    return &RemoveServerSecgroupsRequest{}
}

//response struct for the RemoveServerSecgroups
type RemoveServerSecgroupsResponse struct{
    RemoveServerResult secgroups.RemoveServerResult
}

func NewRemoveServerSecgroupsResponse(removeServerResult secgroups.RemoveServerResult,)*RemoveServerSecgroupsResponse {
    return &RemoveServerSecgroupsResponse{
            RemoveServerResult:removeServerResult,
    }
}

// action function
func (oc *OpenstackClient) RemoveServerSecgroups(request *RemoveServerSecgroupsRequest)(*RemoveServerSecgroupsResponse){
    return NewRemoveServerSecgroupsResponse(secgroups.RemoveServer(oc.client,request.serverID,request.groupName, ))

}