package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/services"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListServices
type ListServicesRequest struct{
    opts services.ListOptsBuilder
}

func NewListServicesRequest()*ListServicesRequest{
    return &ListServicesRequest{}
}

//response struct for the ListServices
type ListServicesResponse struct{
    Pager pagination.Pager
}

func NewListServicesResponse(pager pagination.Pager,)*ListServicesResponse {
    return &ListServicesResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListServices(request *ListServicesRequest)(*ListServicesResponse){
    return NewListServicesResponse(services.List(oc.client,request.opts, ))

}
//request struct for the UpdateServices
type UpdateServicesRequest struct{
    id string
    opts services.UpdateOpts
}

func NewUpdateServicesRequest()*UpdateServicesRequest{
    return &UpdateServicesRequest{}
}

//response struct for the UpdateServices
type UpdateServicesResponse struct{
    UpdateResult services.UpdateResult
}

func NewUpdateServicesResponse(updateResult services.UpdateResult,)*UpdateServicesResponse {
    return &UpdateServicesResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateServices(request *UpdateServicesRequest)(*UpdateServicesResponse){
    return NewUpdateServicesResponse(services.Update(oc.client,request.id,request.opts, ))

}
//request struct for the DeleteServices
type DeleteServicesRequest struct{
    id string
}

func NewDeleteServicesRequest()*DeleteServicesRequest{
    return &DeleteServicesRequest{}
}

//response struct for the DeleteServices
type DeleteServicesResponse struct{
    DeleteResult services.DeleteResult
}

func NewDeleteServicesResponse(deleteResult services.DeleteResult,)*DeleteServicesResponse {
    return &DeleteServicesResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteServices(request *DeleteServicesRequest)(*DeleteServicesResponse){
    return NewDeleteServicesResponse(services.Delete(oc.client,request.id, ))

}