package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharetypes"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateSharedfilesystemsV2Sharetypes
type CreateSharedfilesystemsV2SharetypesRequest struct{
    Opts sharetypes.CreateOpts
}

func NewCreateSharedfilesystemsV2SharetypesRequest()*CreateSharedfilesystemsV2SharetypesRequest{
    return &CreateSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the CreateSharedfilesystemsV2Sharetypes
type CreateSharedfilesystemsV2SharetypesResponse struct{
    CreateResult sharetypes.CreateResult
}

func NewCreateSharedfilesystemsV2SharetypesResponse(createResult sharetypes.CreateResult,)*CreateSharedfilesystemsV2SharetypesResponse {
    return &CreateSharedfilesystemsV2SharetypesResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateSharedfilesystemsV2Sharetypes(req *CreateSharedfilesystemsV2SharetypesRequest)(*CreateSharedfilesystemsV2SharetypesResponse){
    return NewCreateSharedfilesystemsV2SharetypesResponse(sharetypes.Create(oc.Client,req.Opts, ))

}
//request struct for the DeleteSharedfilesystemsV2Sharetypes
type DeleteSharedfilesystemsV2SharetypesRequest struct{
    Id string
}

func NewDeleteSharedfilesystemsV2SharetypesRequest()*DeleteSharedfilesystemsV2SharetypesRequest{
    return &DeleteSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the DeleteSharedfilesystemsV2Sharetypes
type DeleteSharedfilesystemsV2SharetypesResponse struct{
    DeleteResult sharetypes.DeleteResult
}

func NewDeleteSharedfilesystemsV2SharetypesResponse(deleteResult sharetypes.DeleteResult,)*DeleteSharedfilesystemsV2SharetypesResponse {
    return &DeleteSharedfilesystemsV2SharetypesResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteSharedfilesystemsV2Sharetypes(req *DeleteSharedfilesystemsV2SharetypesRequest)(*DeleteSharedfilesystemsV2SharetypesResponse){
    return NewDeleteSharedfilesystemsV2SharetypesResponse(sharetypes.Delete(oc.Client,req.Id, ))

}
//request struct for the ListSharedfilesystemsV2Sharetypes
type ListSharedfilesystemsV2SharetypesRequest struct{
    Opts sharetypes.ListOpts
}

func NewListSharedfilesystemsV2SharetypesRequest()*ListSharedfilesystemsV2SharetypesRequest{
    return &ListSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the ListSharedfilesystemsV2Sharetypes
type ListSharedfilesystemsV2SharetypesResponse struct{
    Pager pagination.Pager
}

func NewListSharedfilesystemsV2SharetypesResponse(pager pagination.Pager,)*ListSharedfilesystemsV2SharetypesResponse {
    return &ListSharedfilesystemsV2SharetypesResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListSharedfilesystemsV2Sharetypes(req *ListSharedfilesystemsV2SharetypesRequest)(*ListSharedfilesystemsV2SharetypesResponse){
    return NewListSharedfilesystemsV2SharetypesResponse(sharetypes.List(oc.Client,req.Opts, ))

}
//request struct for the GetExtraSpecsSharedfilesystemsV2Sharetypes
type GetExtraSpecsSharedfilesystemsV2SharetypesRequest struct{
    Id string
}

func NewGetExtraSpecsSharedfilesystemsV2SharetypesRequest()*GetExtraSpecsSharedfilesystemsV2SharetypesRequest{
    return &GetExtraSpecsSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the GetExtraSpecsSharedfilesystemsV2Sharetypes
type GetExtraSpecsSharedfilesystemsV2SharetypesResponse struct{
    GetExtraSpecsResult sharetypes.GetExtraSpecsResult
}

func NewGetExtraSpecsSharedfilesystemsV2SharetypesResponse(getExtraSpecsResult sharetypes.GetExtraSpecsResult,)*GetExtraSpecsSharedfilesystemsV2SharetypesResponse {
    return &GetExtraSpecsSharedfilesystemsV2SharetypesResponse{
            GetExtraSpecsResult:getExtraSpecsResult,
    }
}

// action function
func (oc *OpenstackClient) GetExtraSpecsSharedfilesystemsV2Sharetypes(req *GetExtraSpecsSharedfilesystemsV2SharetypesRequest)(*GetExtraSpecsSharedfilesystemsV2SharetypesResponse){
    return NewGetExtraSpecsSharedfilesystemsV2SharetypesResponse(sharetypes.GetExtraSpecs(oc.Client,req.Id, ))

}
//request struct for the SetExtraSpecsSharedfilesystemsV2Sharetypes
type SetExtraSpecsSharedfilesystemsV2SharetypesRequest struct{
    Id string
    Opts sharetypes.SetExtraSpecsOpts
}

func NewSetExtraSpecsSharedfilesystemsV2SharetypesRequest()*SetExtraSpecsSharedfilesystemsV2SharetypesRequest{
    return &SetExtraSpecsSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the SetExtraSpecsSharedfilesystemsV2Sharetypes
type SetExtraSpecsSharedfilesystemsV2SharetypesResponse struct{
    SetExtraSpecsResult sharetypes.SetExtraSpecsResult
}

func NewSetExtraSpecsSharedfilesystemsV2SharetypesResponse(setExtraSpecsResult sharetypes.SetExtraSpecsResult,)*SetExtraSpecsSharedfilesystemsV2SharetypesResponse {
    return &SetExtraSpecsSharedfilesystemsV2SharetypesResponse{
            SetExtraSpecsResult:setExtraSpecsResult,
    }
}

// action function
func (oc *OpenstackClient) SetExtraSpecsSharedfilesystemsV2Sharetypes(req *SetExtraSpecsSharedfilesystemsV2SharetypesRequest)(*SetExtraSpecsSharedfilesystemsV2SharetypesResponse){
    return NewSetExtraSpecsSharedfilesystemsV2SharetypesResponse(sharetypes.SetExtraSpecs(oc.Client,req.Id,req.Opts, ))

}
//request struct for the UnsetExtraSpecsSharedfilesystemsV2Sharetypes
type UnsetExtraSpecsSharedfilesystemsV2SharetypesRequest struct{
    Id string
    Key string
}

func NewUnsetExtraSpecsSharedfilesystemsV2SharetypesRequest()*UnsetExtraSpecsSharedfilesystemsV2SharetypesRequest{
    return &UnsetExtraSpecsSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the UnsetExtraSpecsSharedfilesystemsV2Sharetypes
type UnsetExtraSpecsSharedfilesystemsV2SharetypesResponse struct{
    UnsetExtraSpecsResult sharetypes.UnsetExtraSpecsResult
}

func NewUnsetExtraSpecsSharedfilesystemsV2SharetypesResponse(unsetExtraSpecsResult sharetypes.UnsetExtraSpecsResult,)*UnsetExtraSpecsSharedfilesystemsV2SharetypesResponse {
    return &UnsetExtraSpecsSharedfilesystemsV2SharetypesResponse{
            UnsetExtraSpecsResult:unsetExtraSpecsResult,
    }
}

// action function
func (oc *OpenstackClient) UnsetExtraSpecsSharedfilesystemsV2Sharetypes(req *UnsetExtraSpecsSharedfilesystemsV2SharetypesRequest)(*UnsetExtraSpecsSharedfilesystemsV2SharetypesResponse){
    return NewUnsetExtraSpecsSharedfilesystemsV2SharetypesResponse(sharetypes.UnsetExtraSpecs(oc.Client,req.Id,req.Key, ))

}
//request struct for the ShowAccessSharedfilesystemsV2Sharetypes
type ShowAccessSharedfilesystemsV2SharetypesRequest struct{
    Id string
}

func NewShowAccessSharedfilesystemsV2SharetypesRequest()*ShowAccessSharedfilesystemsV2SharetypesRequest{
    return &ShowAccessSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the ShowAccessSharedfilesystemsV2Sharetypes
type ShowAccessSharedfilesystemsV2SharetypesResponse struct{
    ShowAccessResult sharetypes.ShowAccessResult
}

func NewShowAccessSharedfilesystemsV2SharetypesResponse(showAccessResult sharetypes.ShowAccessResult,)*ShowAccessSharedfilesystemsV2SharetypesResponse {
    return &ShowAccessSharedfilesystemsV2SharetypesResponse{
            ShowAccessResult:showAccessResult,
    }
}

// action function
func (oc *OpenstackClient) ShowAccessSharedfilesystemsV2Sharetypes(req *ShowAccessSharedfilesystemsV2SharetypesRequest)(*ShowAccessSharedfilesystemsV2SharetypesResponse){
    return NewShowAccessSharedfilesystemsV2SharetypesResponse(sharetypes.ShowAccess(oc.Client,req.Id, ))

}
//request struct for the AddAccessSharedfilesystemsV2Sharetypes
type AddAccessSharedfilesystemsV2SharetypesRequest struct{
    Id string
    Opts sharetypes.AccessOpts
}

func NewAddAccessSharedfilesystemsV2SharetypesRequest()*AddAccessSharedfilesystemsV2SharetypesRequest{
    return &AddAccessSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the AddAccessSharedfilesystemsV2Sharetypes
type AddAccessSharedfilesystemsV2SharetypesResponse struct{
    AddAccessResult sharetypes.AddAccessResult
}

func NewAddAccessSharedfilesystemsV2SharetypesResponse(addAccessResult sharetypes.AddAccessResult,)*AddAccessSharedfilesystemsV2SharetypesResponse {
    return &AddAccessSharedfilesystemsV2SharetypesResponse{
            AddAccessResult:addAccessResult,
    }
}

// action function
func (oc *OpenstackClient) AddAccessSharedfilesystemsV2Sharetypes(req *AddAccessSharedfilesystemsV2SharetypesRequest)(*AddAccessSharedfilesystemsV2SharetypesResponse){
    return NewAddAccessSharedfilesystemsV2SharetypesResponse(sharetypes.AddAccess(oc.Client,req.Id,req.Opts, ))

}
//request struct for the RemoveAccessSharedfilesystemsV2Sharetypes
type RemoveAccessSharedfilesystemsV2SharetypesRequest struct{
    Id string
    Opts sharetypes.AccessOpts
}

func NewRemoveAccessSharedfilesystemsV2SharetypesRequest()*RemoveAccessSharedfilesystemsV2SharetypesRequest{
    return &RemoveAccessSharedfilesystemsV2SharetypesRequest{}
}

//response struct for the RemoveAccessSharedfilesystemsV2Sharetypes
type RemoveAccessSharedfilesystemsV2SharetypesResponse struct{
    RemoveAccessResult sharetypes.RemoveAccessResult
}

func NewRemoveAccessSharedfilesystemsV2SharetypesResponse(removeAccessResult sharetypes.RemoveAccessResult,)*RemoveAccessSharedfilesystemsV2SharetypesResponse {
    return &RemoveAccessSharedfilesystemsV2SharetypesResponse{
            RemoveAccessResult:removeAccessResult,
    }
}

// action function
func (oc *OpenstackClient) RemoveAccessSharedfilesystemsV2Sharetypes(req *RemoveAccessSharedfilesystemsV2SharetypesRequest)(*RemoveAccessSharedfilesystemsV2SharetypesResponse){
    return NewRemoveAccessSharedfilesystemsV2SharetypesResponse(sharetypes.RemoveAccess(oc.Client,req.Id,req.Opts, ))

}