package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/schedulerstats"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the ListSharedfilesystemsV2Schedulerstats
type ListSharedfilesystemsV2SchedulerstatsRequest struct{
    Opts schedulerstats.ListOptsBuilder
}

func NewListSharedfilesystemsV2SchedulerstatsRequest()*ListSharedfilesystemsV2SchedulerstatsRequest{
    return &ListSharedfilesystemsV2SchedulerstatsRequest{}
}

//response struct for the ListSharedfilesystemsV2Schedulerstats
type ListSharedfilesystemsV2SchedulerstatsResponse struct{
    Pager pagination.Pager
}

func NewListSharedfilesystemsV2SchedulerstatsResponse(pager pagination.Pager,)*ListSharedfilesystemsV2SchedulerstatsResponse {
    return &ListSharedfilesystemsV2SchedulerstatsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListSharedfilesystemsV2Schedulerstats(request *ListSharedfilesystemsV2SchedulerstatsRequest)(*ListSharedfilesystemsV2SchedulerstatsResponse){
    return NewListSharedfilesystemsV2SchedulerstatsResponse(schedulerstats.List(oc.client,request.Opts, ))

}
//request struct for the ListDetailSharedfilesystemsV2Schedulerstats
type ListDetailSharedfilesystemsV2SchedulerstatsRequest struct{
    Opts schedulerstats.ListDetailOptsBuilder
}

func NewListDetailSharedfilesystemsV2SchedulerstatsRequest()*ListDetailSharedfilesystemsV2SchedulerstatsRequest{
    return &ListDetailSharedfilesystemsV2SchedulerstatsRequest{}
}

//response struct for the ListDetailSharedfilesystemsV2Schedulerstats
type ListDetailSharedfilesystemsV2SchedulerstatsResponse struct{
    Pager pagination.Pager
}

func NewListDetailSharedfilesystemsV2SchedulerstatsResponse(pager pagination.Pager,)*ListDetailSharedfilesystemsV2SchedulerstatsResponse {
    return &ListDetailSharedfilesystemsV2SchedulerstatsResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListDetailSharedfilesystemsV2Schedulerstats(request *ListDetailSharedfilesystemsV2SchedulerstatsRequest)(*ListDetailSharedfilesystemsV2SchedulerstatsResponse){
    return NewListDetailSharedfilesystemsV2SchedulerstatsResponse(schedulerstats.ListDetail(oc.client,request.Opts, ))

}