package openstack

// Code generated by cloud manager.





import (
    "github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/securityservices"
    "github.com/gophercloud/gophercloud/pagination"
)
//request struct for the CreateSharedfilesystemsV2Securityservices
type CreateSharedfilesystemsV2SecurityservicesRequest struct{
    Opts securityservices.CreateOptsBuilder
}

func NewCreateSharedfilesystemsV2SecurityservicesRequest()*CreateSharedfilesystemsV2SecurityservicesRequest{
    return &CreateSharedfilesystemsV2SecurityservicesRequest{}
}

//response struct for the CreateSharedfilesystemsV2Securityservices
type CreateSharedfilesystemsV2SecurityservicesResponse struct{
    CreateResult securityservices.CreateResult
}

func NewCreateSharedfilesystemsV2SecurityservicesResponse(createResult securityservices.CreateResult,)*CreateSharedfilesystemsV2SecurityservicesResponse {
    return &CreateSharedfilesystemsV2SecurityservicesResponse{
            CreateResult:createResult,
    }
}

// action function
func (oc *OpenstackClient) CreateSharedfilesystemsV2Securityservices(request *CreateSharedfilesystemsV2SecurityservicesRequest)(*CreateSharedfilesystemsV2SecurityservicesResponse){
    return NewCreateSharedfilesystemsV2SecurityservicesResponse(securityservices.Create(oc.client,request.Opts, ))

}
//request struct for the DeleteSharedfilesystemsV2Securityservices
type DeleteSharedfilesystemsV2SecurityservicesRequest struct{
    Id string
}

func NewDeleteSharedfilesystemsV2SecurityservicesRequest()*DeleteSharedfilesystemsV2SecurityservicesRequest{
    return &DeleteSharedfilesystemsV2SecurityservicesRequest{}
}

//response struct for the DeleteSharedfilesystemsV2Securityservices
type DeleteSharedfilesystemsV2SecurityservicesResponse struct{
    DeleteResult securityservices.DeleteResult
}

func NewDeleteSharedfilesystemsV2SecurityservicesResponse(deleteResult securityservices.DeleteResult,)*DeleteSharedfilesystemsV2SecurityservicesResponse {
    return &DeleteSharedfilesystemsV2SecurityservicesResponse{
            DeleteResult:deleteResult,
    }
}

// action function
func (oc *OpenstackClient) DeleteSharedfilesystemsV2Securityservices(request *DeleteSharedfilesystemsV2SecurityservicesRequest)(*DeleteSharedfilesystemsV2SecurityservicesResponse){
    return NewDeleteSharedfilesystemsV2SecurityservicesResponse(securityservices.Delete(oc.client,request.Id, ))

}
//request struct for the ListSharedfilesystemsV2Securityservices
type ListSharedfilesystemsV2SecurityservicesRequest struct{
    Opts securityservices.ListOptsBuilder
}

func NewListSharedfilesystemsV2SecurityservicesRequest()*ListSharedfilesystemsV2SecurityservicesRequest{
    return &ListSharedfilesystemsV2SecurityservicesRequest{}
}

//response struct for the ListSharedfilesystemsV2Securityservices
type ListSharedfilesystemsV2SecurityservicesResponse struct{
    Pager pagination.Pager
}

func NewListSharedfilesystemsV2SecurityservicesResponse(pager pagination.Pager,)*ListSharedfilesystemsV2SecurityservicesResponse {
    return &ListSharedfilesystemsV2SecurityservicesResponse{
            Pager:pager,
    }
}

// action function
func (oc *OpenstackClient) ListSharedfilesystemsV2Securityservices(request *ListSharedfilesystemsV2SecurityservicesRequest)(*ListSharedfilesystemsV2SecurityservicesResponse){
    return NewListSharedfilesystemsV2SecurityservicesResponse(securityservices.List(oc.client,request.Opts, ))

}
//request struct for the GetSharedfilesystemsV2Securityservices
type GetSharedfilesystemsV2SecurityservicesRequest struct{
    Id string
}

func NewGetSharedfilesystemsV2SecurityservicesRequest()*GetSharedfilesystemsV2SecurityservicesRequest{
    return &GetSharedfilesystemsV2SecurityservicesRequest{}
}

//response struct for the GetSharedfilesystemsV2Securityservices
type GetSharedfilesystemsV2SecurityservicesResponse struct{
    GetResult securityservices.GetResult
}

func NewGetSharedfilesystemsV2SecurityservicesResponse(getResult securityservices.GetResult,)*GetSharedfilesystemsV2SecurityservicesResponse {
    return &GetSharedfilesystemsV2SecurityservicesResponse{
            GetResult:getResult,
    }
}

// action function
func (oc *OpenstackClient) GetSharedfilesystemsV2Securityservices(request *GetSharedfilesystemsV2SecurityservicesRequest)(*GetSharedfilesystemsV2SecurityservicesResponse){
    return NewGetSharedfilesystemsV2SecurityservicesResponse(securityservices.Get(oc.client,request.Id, ))

}
//request struct for the UpdateSharedfilesystemsV2Securityservices
type UpdateSharedfilesystemsV2SecurityservicesRequest struct{
    Id string
    Opts securityservices.UpdateOptsBuilder
}

func NewUpdateSharedfilesystemsV2SecurityservicesRequest()*UpdateSharedfilesystemsV2SecurityservicesRequest{
    return &UpdateSharedfilesystemsV2SecurityservicesRequest{}
}

//response struct for the UpdateSharedfilesystemsV2Securityservices
type UpdateSharedfilesystemsV2SecurityservicesResponse struct{
    UpdateResult securityservices.UpdateResult
}

func NewUpdateSharedfilesystemsV2SecurityservicesResponse(updateResult securityservices.UpdateResult,)*UpdateSharedfilesystemsV2SecurityservicesResponse {
    return &UpdateSharedfilesystemsV2SecurityservicesResponse{
            UpdateResult:updateResult,
    }
}

// action function
func (oc *OpenstackClient) UpdateSharedfilesystemsV2Securityservices(request *UpdateSharedfilesystemsV2SecurityservicesRequest)(*UpdateSharedfilesystemsV2SecurityservicesResponse){
    return NewUpdateSharedfilesystemsV2SecurityservicesResponse(securityservices.Update(oc.client,request.Id,request.Opts, ))

}